#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Генератор полного, высококачественного русского перевода для мода Cluttered (1062 ключа).
Полностью исключает любые оставшиеся английские слова и полупереводы.
"""

import json
import os
import re

def build_all_translations():
    with open('tasks/Translate_Mods/completed/translate_cluttered/en_us_all.json', 'r', encoding='utf-8') as f:
        en_us = json.load(f)

    tr = {}

    # 1. Системные и тултипы
    tr["item.cluttered.hand_drill"] = "Ручная дрель"
    tr["cluttered.hand_drill.tooltip"] = "Используется для изменения деталей мебели и текстур блоков.\nПрисядьте (Shift), чтобы вращать блоки.\nТекстура: EyeSeeDee!"
    tr["cluttered.bouncymushroom.tooltip"] = "Он такой прыгучий!"
    tr["cluttered.eye_block.tooltip"] = "Неприлично пялиться..."
    tr["cluttered.garland.tooltip"] = "Можно сдвигать влево и вправо с помощью ручной дрели"
    tr["cluttered.bracket.tooltip"] = "Можно размещать на заборах"
    tr["cluttered.polaroid_camera.tooltip"] = "Попробуйте вставить бумагу!"
    tr["cluttered.storage"] = "Хранилище"
    tr["cluttered.fridge"] = "Холодильник"
    tr["cluttered.box"] = "Картонная коробка"
    tr["creativetab.cluttered_tab"] = "Cluttered: Блоки"
    tr["creativetab.cluttered_furniture_tab"] = "Cluttered: Мебель"

    # 2. Картины
    tr["painting.cluttered.mimikyu.title"] = "Мимикью"
    tr["painting.cluttered.mimikyu.author"] = "YellowChuJelly"
    tr["painting.cluttered.candle.title"] = "Свеча"
    tr["painting.cluttered.candle.author"] = "Blakes"
    tr["painting.cluttered.cat_short.title"] = "Низкий кот"
    tr["painting.cluttered.cat_short.author"] = "Blakes"
    tr["painting.cluttered.crow_on_a_beach.title"] = "Ворона на пляже"
    tr["painting.cluttered.crow_on_a_beach.author"] = "Blakes"
    tr["painting.cluttered.eggplants_lynnhays.title"] = "Баклажаны"
    tr["painting.cluttered.eggplants_lynnhays.author"] = "Lynnhays"
    tr["painting.cluttered.etienne_carolhoffnagle.title"] = "Этьен"
    tr["painting.cluttered.etienne_carolhoffnagle.author"] = "Carol Hoffnagle"
    tr["painting.cluttered.flower_pots.title"] = "Цветочные горшки"
    tr["painting.cluttered.flower_pots.author"] = "Blakes"
    tr["painting.cluttered.lemons.title"] = "Лимоны"
    tr["painting.cluttered.lemons.author"] = "Blakes"
    tr["painting.cluttered.red_mushroom.title"] = "Красный гриб"
    tr["painting.cluttered.red_mushroom.author"] = "Blakes"
    tr["painting.cluttered.stiefmutterchen_heidedahl.title"] = "Анютины глазки"
    tr["painting.cluttered.stiefmutterchen_heidedahl.author"] = "Heide Dahl"
    tr["painting.cluttered.two_cats.title"] = "Два кота"
    tr["painting.cluttered.two_cats.author"] = "Blakes"
    tr["painting.cluttered.cat_tall.title"] = "Высокий кот"
    tr["painting.cluttered.cat_tall.author"] = "Blakes"
    tr["painting.cluttered.day_sky.title"] = "Дневное небо"
    tr["painting.cluttered.day_sky.author"] = "Blakes"
    tr["painting.cluttered.night_sky.title"] = "Ночное небо"
    tr["painting.cluttered.night_sky.author"] = "Blakes"
    tr["painting.cluttered.frogman_washington.title"] = "Человек-лягушка Вашингтон"
    tr["painting.cluttered.frogman_washington.author"] = "YellowChuJelly"
    tr["painting.cluttered.van_gogh_flamenettle.title"] = "Колеус"
    tr["painting.cluttered.van_gogh_flamenettle.author"] = "Ван Гог"
    tr["painting.cluttered.vase_of_sunflowers.title"] = "Ваза с подсолнухами"
    tr["painting.cluttered.vase_of_sunflowers.author"] = "Blakes"
    tr["painting.cluttered.worm.title"] = "Червячок"
    tr["painting.cluttered.worm.author"] = "YellowChuJelly"
    tr["painting.cluttered.pinned_butterflies.title"] = "Бабочки под стеклом"
    tr["painting.cluttered.pinned_butterflies.author"] = "Blakes"
    tr["painting.cluttered.van_gogh_horse.title"] = "Лошадь"
    tr["painting.cluttered.van_gogh_horse.author"] = "Ван Гог"
    tr["painting.cluttered.gold_sunflower.title"] = "Золотой подсолнух"
    tr["painting.cluttered.gold_sunflower.author"] = "Blakes"
    tr["painting.cluttered.van_gogh_wheatfield.title"] = "Пшеничное поле"
    tr["painting.cluttered.van_gogh_wheatfield.author"] = "Ван Гог"
    tr["painting.cluttered.ridley_fire.title"] = "Плазма Ридли"
    tr["painting.cluttered.ridley_fire.author"] = "YellowChuJelly"
    tr["painting.cluttered.ridley_dimension.title"] = "Измерение Ридли"
    tr["painting.cluttered.ridley_dimension.author"] = "RidleyDimensionFan"

    # 3. Древесина и стандартные деревянные наборы
    # ИВА
    tr["block.cluttered.willow_sapling"] = "Саженец ивы"
    tr["block.cluttered.willow_leaves"] = "Листья ивы"
    tr["block.cluttered.willow_vines"] = "Лоза ивы"
    tr["block.cluttered.willow_planks"] = "Ивовые доски"
    tr["block.cluttered.willow_log"] = "Ивовое бревно"
    tr["block.cluttered.willow_wood"] = "Ивовая древесина"
    tr["block.cluttered.stripped_willow_log"] = "Обтёсанное ивовое бревно"
    tr["block.cluttered.stripped_willow_wood"] = "Обтёсанная ивовая древесина"
    tr["block.cluttered.willow_slab"] = "Ивовая плита"
    tr["block.cluttered.willow_stairs"] = "Ивовые ступеньки"
    tr["block.cluttered.willow_fence"] = "Ивовый забор"
    tr["block.cluttered.willow_fence_gate"] = "Ивовая калитка"
    tr["block.cluttered.willow_log_door"] = "Дверь из ивового бревна"
    tr["block.cluttered.willow_garden_door"] = "Ивовая садовая дверь"
    tr["block.cluttered.willow_door"] = "Ивовая дверь"
    tr["block.cluttered.willow_trapdoor"] = "Ивовый люк"
    tr["block.cluttered.willow_button"] = "Ивовая кнопка"
    tr["block.cluttered.willow_sign"] = "Ивовая табличка"
    tr["block.cluttered.willow_hanging_sign"] = "Ивовая подвесная табличка"
    tr["block.cluttered.willow_hanging_sign_item"] = "Ивовая подвесная табличка"
    tr["block.cluttered.willow_pressure_plate"] = "Ивовая нажимная плита"
    tr["block.cluttered.willow_bookshelf_black_cat"] = "Ивовая книжная полка с чёрным котом"
    tr["block.cluttered.willow_bookshelf_calico_cat"] = "Ивовая книжная полка с трёхцветным котом"
    tr["block.cluttered.willow_bookshelf_cobweb"] = "Ивовая книжная полка с паутиной"
    tr["block.cluttered.willow_bookshelf_bottles"] = "Ивовая книжная полка алхимика"
    tr["block.cluttered.willow_bookshelf_vase"] = "Ивовая книжная полка травника"
    tr["block.cluttered.willow_window"] = "Ивовое окно"
    tr["block.cluttered.willow_window_pane"] = "Ивовая оконная рама"
    tr["block.cluttered.flowering_willow_leaves"] = "Цветущие листья ивы"
    tr["block.cluttered.flower_carpet_willow"] = "Ивовый цветочный ковёр"
    tr["block.cluttered.flowering_willow_planks"] = "Цветущие ивовые доски"
    tr["block.cluttered.flowering_willow_log"] = "Цветущее ивовое бревно"
    tr["block.cluttered.flowering_willow_wood"] = "Цветущая ивовая древесина"
    tr["block.cluttered.stripped_flowering_willow_log"] = "Обтёсанное цветущее ивовое бревно"
    tr["block.cluttered.stripped_flowering_willow_wood"] = "Обтёсанная цветущая ивовая древесина"
    tr["block.cluttered.flowering_willow_slab"] = "Цветущая ивовая плита"
    tr["block.cluttered.flowering_willow_stairs"] = "Цветущие ивовые ступеньки"
    tr["block.cluttered.flowering_willow_fence"] = "Цветущий ивовый забор"
    tr["block.cluttered.flowering_willow_fence_gate"] = "Цветущая ивовая калитка"
    tr["block.cluttered.flowering_willow_door"] = "Цветущая ивовая дверь"
    tr["block.cluttered.flowering_willow_trapdoor"] = "Цветущий ивовый люк"
    tr["block.cluttered.flowering_willow_button"] = "Цветущая ивовая кнопка"
    tr["block.cluttered.flowering_willow_sign"] = "Цветущая ивовая табличка"
    tr["block.cluttered.flowering_willow_hanging_sign"] = "Цветущая ивовая подвесная табличка"
    tr["block.cluttered.flowering_willow_pressure_plate"] = "Цветущая ивовая нажимная плита"
    tr["block.cluttered.flowering_willow_window"] = "Цветущее ивовое окно"
    tr["block.cluttered.flowering_willow_window_pane"] = "Цветущая ивовая оконная рама"

    # ТОПОЛЬ
    tr["block.cluttered.poplar_sapling"] = "Саженец тополя"
    tr["block.cluttered.poplar_leaves"] = "Листья тополя"
    tr["block.cluttered.poplar_planks"] = "Тополиные доски"
    tr["block.cluttered.poplar_log"] = "Тополиное бревно"
    tr["block.cluttered.poplar_wood"] = "Тополиная древесина"
    tr["block.cluttered.stripped_poplar_log"] = "Обтёсанное тополиное бревно"
    tr["block.cluttered.stripped_poplar_wood"] = "Обтёсанная тополиная древесина"
    tr["block.cluttered.poplar_slab"] = "Тополиная плита"
    tr["block.cluttered.poplar_stairs"] = "Тополиные ступеньки"
    tr["block.cluttered.poplar_fence"] = "Тополиный забор"
    tr["block.cluttered.poplar_fence_gate"] = "Тополиная калитка"
    tr["block.cluttered.poplar_door"] = "Тополиная дверь"
    tr["block.cluttered.poplar_trapdoor"] = "Тополиный люк"
    tr["block.cluttered.poplar_button"] = "Тополиная кнопка"
    tr["block.cluttered.poplar_sign"] = "Тополиная табличка"
    tr["block.cluttered.poplar_hanging_sign"] = "Тополиная подвесная табличка"
    tr["block.cluttered.poplar_pressure_plate"] = "Тополиная нажимная плита"
    tr["block.cluttered.poplar_window"] = "Тополиное окно"
    tr["block.cluttered.poplar_window_pane"] = "Тополиная оконная рама"
    tr["block.cluttered.poplar_bookshelf"] = "Тополиная книжная полка"
    tr["block.cluttered.flowering_poplar_leaves"] = "Цветущие листья тополя"
    tr["block.cluttered.flower_carpet_poplar"] = "Тополиный цветочный ковёр"
    tr["block.cluttered.flowering_poplar_planks"] = "Цветущие тополиные доски"
    tr["block.cluttered.flowering_poplar_log"] = "Цветущее тополиное бревно"
    tr["block.cluttered.flowering_poplar_wood"] = "Цветущая тополиная древесина"
    tr["block.cluttered.stripped_flowering_poplar_log"] = "Обтёсанное цветущее тополиное бревно"
    tr["block.cluttered.stripped_flowering_poplar_wood"] = "Обтёсанная цветущая тополиная древесина"
    tr["block.cluttered.flowering_poplar_slab"] = "Цветущая тополиная плита"
    tr["block.cluttered.flowering_poplar_stairs"] = "Цветущие тополиные ступеньки"
    tr["block.cluttered.flowering_poplar_fence"] = "Цветущий тополиный забор"
    tr["block.cluttered.flowering_poplar_fence_gate"] = "Цветущая тополиная калитка"
    tr["block.cluttered.flowering_poplar_door"] = "Цветущая тополиная дверь"
    tr["block.cluttered.flowering_poplar_trapdoor"] = "Цветущий тополиный люк"
    tr["block.cluttered.flowering_poplar_button"] = "Цветущая тополиная кнопка"
    tr["block.cluttered.flowering_poplar_sign"] = "Цветущая тополиная табличка"
    tr["block.cluttered.flowering_poplar_hanging_sign"] = "Цветущая тополиная подвесная табличка"
    tr["block.cluttered.flowering_poplar_pressure_plate"] = "Цветущая тополиная нажимная плита"
    tr["block.cluttered.flowering_poplar_window"] = "Цветущее тополиное окно"
    tr["block.cluttered.flowering_poplar_window_pane"] = "Цветущая тополиная оконная рама"
    tr["block.cluttered.flowering_poplar_bookshelf"] = "Цветущая тополиная книжная полка"

    # ДИКАЯ ЯБЛОНЯ
    tr["block.cluttered.crabapple_leaves"] = "Листья дикой яблони"
    tr["block.cluttered.crabapple_planks"] = "Доски из дикой яблони"
    tr["block.cluttered.crabapple_sapling"] = "Саженец дикой яблони"
    tr["block.cluttered.crabapple_log"] = "Бревно дикой яблони"
    tr["block.cluttered.crabapple_wood"] = "Древесина дикой яблони"
    tr["block.cluttered.stripped_crabapple_log"] = "Обтёсанное бревно дикой яблони"
    tr["block.cluttered.stripped_crabapple_wood"] = "Обтёсанная древесина дикой яблони"
    tr["block.cluttered.crabapple_slab"] = "Плита из дикой яблони"
    tr["block.cluttered.crabapple_stairs"] = "Ступеньки из дикой яблони"
    tr["block.cluttered.crabapple_fence"] = "Забор из дикой яблони"
    tr["block.cluttered.crabapple_fence_gate"] = "Калитка из дикой яблони"
    tr["block.cluttered.crabapple_door"] = "Дверь из дикой яблони"
    tr["block.cluttered.crabapple_trapdoor"] = "Люк из дикой яблони"
    tr["block.cluttered.crabapple_button"] = "Кнопка из дикой яблони"
    tr["block.cluttered.crabapple_sign"] = "Табличка из дикой яблони"
    tr["block.cluttered.crabapple_hanging_sign"] = "Подвесная табличка из дикой яблони"
    tr["block.cluttered.crabapple_pressure_plate"] = "Нажимная плита из дикой яблони"
    tr["block.cluttered.crabapple_window"] = "Окно из дикой яблони"
    tr["block.cluttered.crabapple_window_pane"] = "Оконная рама из дикой яблони"
    tr["block.cluttered.crabapple_bookshelf"] = "Книжная полка из дикой яблони"
    tr["block.cluttered.flowering_crabapple_leaves"] = "Цветущие листья дикой яблони"
    tr["block.cluttered.flower_carpet_crabapple"] = "Цветочный ковёр из дикой яблони"
    tr["block.cluttered.flowering_crabapple_planks"] = "Цветущие доски из дикой яблони"
    tr["block.cluttered.flowering_crabapple_log"] = "Цветущее бревно дикой яблони"
    tr["block.cluttered.flowering_crabapple_wood"] = "Цветущая древесина дикой яблони"
    tr["block.cluttered.stripped_flowering_crabapple_log"] = "Обтёсанное цветущее бревно дикой яблони"
    tr["block.cluttered.stripped_flowering_crabapple_wood"] = "Обтёсанная цветущая древесина дикой яблони"
    tr["block.cluttered.flowering_crabapple_slab"] = "Цветущая плита из дикой яблони"
    tr["block.cluttered.flowering_crabapple_stairs"] = "Цветущие ступеньки из дикой яблони"
    tr["block.cluttered.flowering_crabapple_fence"] = "Цветущий забор из дикой яблони"
    tr["block.cluttered.flowering_crabapple_fence_gate"] = "Цветущая калитка из дикой яблони"
    tr["block.cluttered.flowering_crabapple_door"] = "Цветущая дверь из дикой яблони"
    tr["block.cluttered.flowering_crabapple_trapdoor"] = "Цветущий люк из дикой яблони"
    tr["block.cluttered.flowering_crabapple_button"] = "Цветущая кнопка из дикой яблони"
    tr["block.cluttered.flowering_crabapple_sign"] = "Цветущая табличка из дикой яблони"
    tr["block.cluttered.flowering_crabapple_hanging_sign"] = "Цветущая подвесная табличка из дикой яблони"
    tr["block.cluttered.flowering_crabapple_pressure_plate"] = "Цветущая нажимная плита из дикой яблони"
    tr["block.cluttered.flowering_crabapple_window"] = "Цветущее окно из дикой яблони"
    tr["block.cluttered.flowering_crabapple_window_pane"] = "Цветущая оконная рама из дикой яблони"
    tr["block.cluttered.flowering_crabapple_bookshelf"] = "Цветущая книжная полка из дикой яблони"

    # ПЛАТАН
    tr["block.cluttered.sycamore_sapling"] = "Саженец платана"
    tr["block.cluttered.sycamore_leaves"] = "Листья платана"
    tr["block.cluttered.sycamore_planks"] = "Платановые доски"
    tr["block.cluttered.sycamore_log"] = "Платановое бревно"
    tr["block.cluttered.sycamore_wood"] = "Платановая древесина"
    tr["block.cluttered.stripped_sycamore_log"] = "Обтёсанное платановое бревно"
    tr["block.cluttered.stripped_sycamore_wood"] = "Обтёсанная платановая древесина"
    tr["block.cluttered.sycamore_slab"] = "Платановая плита"
    tr["block.cluttered.sycamore_stairs"] = "Платановые ступеньки"
    tr["block.cluttered.sycamore_fence"] = "Платановый забор"
    tr["block.cluttered.sycamore_fence_gate"] = "Платановая калитка"
    tr["block.cluttered.sycamore_door"] = "Платановая дверь"
    tr["block.cluttered.sycamore_trapdoor"] = "Платановый люк"
    tr["block.cluttered.sycamore_button"] = "Платановая кнопка"
    tr["block.cluttered.sycamore_sign"] = "Платановая табличка"
    tr["block.cluttered.sycamore_hanging_sign"] = "Платановая подвесная табличка"
    tr["block.cluttered.sycamore_pressure_plate"] = "Платановая нажимная плита"
    tr["block.cluttered.sycamore_window"] = "Платановое окно"
    tr["block.cluttered.sycamore_window_pane"] = "Платановая оконная рама"
    tr["block.cluttered.sycamore_bookshelf"] = "Платановая книжная полка"

    # ЛЮМИНЕСЦЕНТНЫЙ КЛЁН
    tr["block.cluttered.fluorescent_maple_sapling"] = "Саженец люминесцентного клёна"
    tr["block.cluttered.fluorescent_maple_leaves"] = "Листья люминесцентного клёна"
    tr["block.cluttered.flowering_fluorescent_maple_leaves"] = "Цветущие листья люминесцентного клёна"
    tr["block.cluttered.fluorescent_maple_planks"] = "Доски из люминесцентного клёна"
    tr["block.cluttered.fluorescent_maple_log"] = "Бревно люминесцентного клёна"
    tr["block.cluttered.fluorescent_maple_wood"] = "Древесина люминесцентного клёна"
    tr["block.cluttered.stripped_fluorescent_maple_log"] = "Обтёсанное бревно люминесцентного клёна"
    tr["block.cluttered.stripped_fluorescent_maple_wood"] = "Обтёсанная древесина люминесцентного клёна"
    tr["block.cluttered.fluorescent_maple_slab"] = "Плита из люминесцентного клёна"
    tr["block.cluttered.fluorescent_maple_stairs"] = "Ступеньки из люминесцентного клёна"
    tr["block.cluttered.fluorescent_maple_fence"] = "Забор из люминесцентного клёна"
    tr["block.cluttered.fluorescent_maple_fence_gate"] = "Калитка из люминесцентного клёна"
    tr["block.cluttered.fluorescent_maple_door"] = "Дверь из люминесцентного клёна"
    tr["block.cluttered.fluorescent_maple_trapdoor"] = "Люк из люминесцентного клёна"
    tr["block.cluttered.fluorescent_maple_button"] = "Кнопка из люминесцентного клёна"
    tr["block.cluttered.fluorescent_maple_sign"] = "Табличка из люминесцентного клёна"
    tr["block.cluttered.fluorescent_maple_hanging_sign"] = "Подвесная табличка из люминесцентного клёна"
    tr["block.cluttered.fluorescent_maple_pressure_plate"] = "Нажимная плита из люминесцентного клёна"
    tr["block.cluttered.fluorescent_maple_window"] = "Окно из люминесцентного клёна"
    tr["block.cluttered.fluorescent_maple_window_pane"] = "Оконная рама из люминесцентного клёна"
    tr["block.cluttered.fluorescent_maple_bookshelf"] = "Книжная полка из люминесцентного клёна"

    # СИНИЙ ГРИБ (СТРОФАРИЯ)
    tr["block.cluttered.blue_roundhead"] = "Синяя строфария"
    tr["block.cluttered.blue_mushroom_planks"] = "Доски из синего гриба"
    tr["block.cluttered.blue_mushroom_cap"] = "Шляпка синего гриба"
    tr["block.cluttered.blue_mushroom_log"] = "Ножка синего гриба"
    tr["block.cluttered.blue_mushroom_wood"] = "Гифы синего гриба"
    tr["block.cluttered.blue_mushroom_slab"] = "Плита из синего гриба"
    tr["block.cluttered.blue_mushroom_stairs"] = "Ступеньки из синего гриба"
    tr["block.cluttered.blue_mushroom_fence"] = "Забор из синего гриба"
    tr["block.cluttered.blue_mushroom_fence_gate"] = "Калитка из синего гриба"
    tr["block.cluttered.blue_mushroom_door"] = "Дверь из синего гриба"
    tr["block.cluttered.blue_mushroom_trapdoor"] = "Люк из синего гриба"
    tr["block.cluttered.blue_mushroom_button"] = "Кнопка из синего гриба"
    tr["block.cluttered.blue_mushroom_sign"] = "Табличка из синего гриба"
    tr["block.cluttered.blue_mushroom_hanging_sign"] = "Подвесная табличка из синего гриба"
    tr["block.cluttered.blue_mushroom_pressure_plate"] = "Нажимная плита из синего гриба"
    tr["block.cluttered.blue_mushroom_window"] = "Окно из синего гриба"
    tr["block.cluttered.blue_mushroom_window_pane"] = "Оконная рама из синего гриба"
    tr["block.cluttered.blue_mushroom_bookshelf"] = "Книжная полка из синего гриба"

    # КРАСНЫЙ МУХОМОР / КРАСНЫЙ ГРИБ
    tr["block.cluttered.fly_agaric"] = "Красный мухомор"
    tr["block.cluttered.red_mushroom_planks"] = "Доски из красного гриба"
    tr["block.cluttered.red_mushroom_cap"] = "Шляпка красного гриба"
    tr["block.cluttered.red_mushroom_log"] = "Ножка красного гриба"
    tr["block.cluttered.red_mushroom_wood"] = "Гифы красного гриба"
    tr["block.cluttered.red_mushroom_slab"] = "Плита из красного гриба"
    tr["block.cluttered.red_mushroom_stairs"] = "Ступеньки из красного гриба"
    tr["block.cluttered.red_mushroom_fence"] = "Забор из красного гриба"
    tr["block.cluttered.red_mushroom_fence_gate"] = "Калитка из красного гриба"
    tr["block.cluttered.red_mushroom_door"] = "Дверь из красного гриба"
    tr["block.cluttered.red_mushroom_trapdoor"] = "Люк из красного гриба"
    tr["block.cluttered.red_mushroom_button"] = "Кнопка из красного гриба"
    tr["block.cluttered.red_mushroom_sign"] = "Табличка из красного гриба"
    tr["block.cluttered.red_mushroom_hanging_sign"] = "Подвесная табличка из красного гриба"
    tr["block.cluttered.red_mushroom_pressure_plate"] = "Нажимная плита из красного гриба"
    tr["block.cluttered.red_mushroom_window"] = "Окно из красного гриба"
    tr["block.cluttered.red_mushroom_window_pane"] = "Оконная рама из красного гриба"
    tr["block.cluttered.red_mushroom_bookshelf"] = "Книжная полка из красного гриба"

    # ХАЛЦЕДОН
    tr["block.cluttered.raw_chalcedony"] = "Халцедон"
    tr["block.cluttered.chalcedony_stairs"] = "Ступеньки из халцедона"
    tr["block.cluttered.chalcedony_slab"] = "Плита из халцедона"
    tr["block.cluttered.chalcedony_polished"] = "Полированный халцедон"
    tr["block.cluttered.chalcedony_bricks"] = "Халцедоновые кирпичи"
    tr["block.cluttered.chalcedony_brick_stairs"] = "Ступеньки из халцедоновых кирпичей"
    tr["block.cluttered.chalcedony_brick_slab"] = "Плита из халцедоновых кирпичей"
    tr["block.cluttered.chalcedony_chiseled_block"] = "Резной халцедон"
    tr["block.cluttered.chalcedony_border"] = "Окаймлённый халцедон"
    tr["block.cluttered.chalcedony_acanthus"] = "Халцедон с акантом"
    tr["block.cluttered.chalcedony_helix"] = "Халцедон со спиралью"
    tr["block.cluttered.chalcedony_meander"] = "Халцедон с меандром"
    tr["block.cluttered.textile_block_chalcedony"] = "Халцедоновый тканевый блок"
    tr["block.cluttered.chalcedony_chalcedony_border"] = "Окаймлённый халцедон"
    tr["block.cluttered.chalcedony_tiles"] = "Халцедоновая плитка"
    tr["block.cluttered.chalcedony_subway_tiles"] = "Халцедоновая плитка «метро»"
    tr["block.cluttered.chalcedony_pillar"] = "Халцедоновая колонна"
    tr["block.cluttered.chalcedony_pillar_base"] = "База халцедоновой колонны"
    tr["block.cluttered.chalcedony_pillar_doric"] = "Дорическая халцедоновая колонна"
    tr["block.cluttered.chalcedony_pillar_ionic"] = "Ионическая халцедоновая колонна"
    tr["block.cluttered.chalcedony_pillar_starry"] = "Звёздная халцедоновая колонна"
    tr["block.cluttered.chalcedony_pillar_starry_base"] = "База звёздной халцедоновой колонны"
    tr["block.cluttered.chalcedony_pillar_starry_doric"] = "Звёздная дорическая халцедоновая колонна"
    tr["block.cluttered.chalcedony_pillar_starry_ionic"] = "Звёздная ионическая халцедоновая колонна"
    tr["block.cluttered.chalcedony_sun_block"] = "Халцедоновая звезда"
    tr["block.cluttered.chalcedony_window"] = "Халцедоновое окно"
    tr["block.cluttered.chalcedony_window_pane"] = "Халцедоновая оконная рама"
    tr["block.cluttered.chalcedony_balustrade"] = "Халцедоновая балюстрада"
    tr["block.cluttered.chalcedony_picket_fence"] = "Халцедоновый штакетник"
    tr["block.cluttered.chalcedony_picket_fence_gate"] = "Калитка из халцедонового штакетника"
    tr["block.cluttered.chalcedony_victorian_bracket"] = "Халцедоновый викторианский кронштейн"
    tr["block.cluttered.chalcedony_victorian_bracket_scroll"] = "Халцедоновый кронштейн с завитком"
    tr["block.cluttered.chalcedony_victorian_bracket_bow"] = "Халцедоновый кронштейн с бантом"
    tr["block.cluttered.chalcedony_victorian_bracket_bow_scroll"] = "Халцедоновый кронштейн с бантом и завитком"
    tr["block.cluttered.chalcedony_victorian_bracket_star"] = "Халцедоновый кронштейн со звездой"
    tr["block.cluttered.chalcedony_victorian_bracket_star_scroll"] = "Халцедоновый кронштейн со звездой и завитком"
    tr["block.cluttered.chalcedony_victorian_bracket_scroll_shelf"] = "Халцедоновая полка с кронштейном"

    # ГЛУБИННЫЙ ХАЛЦЕДОН
    tr["block.cluttered.deep_raw_chalcedony"] = "Глубинный халцедон"
    tr["block.cluttered.deep_chalcedony_stairs"] = "Ступеньки из глубинного халцедона"
    tr["block.cluttered.deep_chalcedony_slab"] = "Плита из глубинного халцедона"
    tr["block.cluttered.deep_chalcedony_polished"] = "Полированный глубинный халцедон"
    tr["block.cluttered.deep_chalcedony_bricks"] = "Кирпичи из глубинного халцедона"
    tr["block.cluttered.deep_chalcedony_brick_stairs"] = "Ступеньки из кирпичей глубинного халцедона"
    tr["block.cluttered.deep_chalcedony_brick_slab"] = "Плита из кирпичей глубинного халцедона"
    tr["block.cluttered.deep_chalcedony_chiseled_block"] = "Резной глубинный халцедон"
    tr["block.cluttered.deep_chalcedony_border"] = "Окаймлённый глубинный халцедон"
    tr["block.cluttered.deep_chalcedony_acanthus"] = "Глубинный халцедон с акантом"
    tr["block.cluttered.deep_chalcedony_helix"] = "Глубинный халцедон со спиралью"
    tr["block.cluttered.deep_chalcedony_meander"] = "Глубинный халцедон с меандром"
    tr["block.cluttered.textile_block_deep_chalcedony"] = "Тканевый блок из глубинного халцедона"
    tr["block.cluttered.deep_chalcedony_tiles"] = "Плитка из глубинного халцедона"
    tr["block.cluttered.deep_chalcedony_subway_tiles"] = "Плитка «метро» из глубинного халцедона"
    tr["block.cluttered.deep_chalcedony_pillar"] = "Колонна из глубинного халцедона"
    tr["block.cluttered.deep_chalcedony_pillar_base"] = "База колонны из глубинного халцедона"
    tr["block.cluttered.deep_chalcedony_pillar_doric"] = "Дорическая колонна из глубинного халцедона"
    tr["block.cluttered.deep_chalcedony_pillar_ionic"] = "Ионическая колонна из глубинного халцедона"
    tr["block.cluttered.deep_chalcedony_pillar_starry"] = "Звёздная колонна из глубинного халцедона"
    tr["block.cluttered.deep_chalcedony_pillar_starry_base"] = "База звёздной колонны из глубинного халцедона"
    tr["block.cluttered.deep_chalcedony_pillar_starry_doric"] = "Звёздная дорическая колонна из глубинного халцедона"
    tr["block.cluttered.deep_chalcedony_pillar_starry_ionic"] = "Звёздная ионическая колонна из глубинного халцедона"
    tr["block.cluttered.deep_chalcedony_sun_block"] = "Звезда из глубинного халцедона"
    tr["block.cluttered.deep_chalcedony_window"] = "Окно из глубинного халцедона"
    tr["block.cluttered.deep_chalcedony_window_pane"] = "Оконная рама из глубинного халцедона"
    tr["block.cluttered.deep_chalcedony_balustrade"] = "Балюстрада из глубинного халцедона"
    tr["block.cluttered.deep_chalcedony_picket_fence"] = "Штакетник из глубинного халцедона"
    tr["block.cluttered.deep_chalcedony_picket_fence_gate"] = "Калитка из штакетника из глубинного халцедона"
    tr["block.cluttered.deep_chalcedony_victorian_bracket"] = "Викторианский кронштейн из глубинного халцедона"
    tr["block.cluttered.deep_chalcedony_victorian_bracket_scroll"] = "Кронштейн с завитком из глубинного халцедона"
    tr["block.cluttered.deep_chalcedony_victorian_bracket_bow"] = "Кронштейн с бантом из глубинного халцедона"
    tr["block.cluttered.deep_chalcedony_victorian_bracket_bow_scroll"] = "Кронштейн с бантом и завитком из глубинного халцедона"
    tr["block.cluttered.deep_chalcedony_victorian_bracket_star"] = "Кронштейн со звездой из глубинного халцедона"
    tr["block.cluttered.deep_chalcedony_victorian_bracket_star_scroll"] = "Кронштейн со звездой и завитком из глубинного халцедона"
    tr["block.cluttered.deep_chalcedony_victorian_bracket_scroll_shelf"] = "Полка с кронштейном из глубинного халцедона"

    # МРАМОР
    tr["block.cluttered.raw_marble"] = "Мрамор"
    tr["block.cluttered.marble_stairs"] = "Мраморные ступеньки"
    tr["block.cluttered.marble_slab"] = "Мраморная плита"
    tr["block.cluttered.marble_polished"] = "Полированный мрамор"
    tr["block.cluttered.marble_bricks"] = "Мраморные кирпичи"
    tr["block.cluttered.marble_brick_stairs"] = "Ступеньки из мраморных кирпичей"
    tr["block.cluttered.marble_brick_slab"] = "Плита из мраморных кирпичей"
    tr["block.cluttered.marble_chiseled_block"] = "Резной мрамор"
    tr["block.cluttered.marble_border"] = "Окаймлённый мрамор"
    tr["block.cluttered.marble_acanthus"] = "Мрамор с акантом"
    tr["block.cluttered.marble_helix"] = "Мрамор со спиралью"
    tr["block.cluttered.marble_meander"] = "Мрамор с меандром"
    tr["block.cluttered.textile_block_marble"] = "Мраморный тканевый блок"
    tr["block.cluttered.marble_marble_border"] = "Окаймлённый мрамор"
    tr["block.cluttered.marble_tiles"] = "Мраморная плитка"
    tr["block.cluttered.marble_subway_tiles"] = "Мраморная плитка «метро»"
    tr["block.cluttered.marble_pillar"] = "Мраморная колонна"
    tr["block.cluttered.marble_pillar_base"] = "База мраморной колонны"
    tr["block.cluttered.marble_pillar_doric"] = "Дорическая мраморная колонна"
    tr["block.cluttered.marble_pillar_ionic"] = "Ионическая мраморная колонна"
    tr["block.cluttered.marble_sun_block"] = "Мраморная звезда"
    tr["block.cluttered.marble_balustrade"] = "Мраморная балюстрада"
    tr["block.cluttered.marble_picket_fence"] = "Мраморный штакетник"
    tr["block.cluttered.marble_picket_fence_gate"] = "Калитка из мраморного штакетника"
    tr["block.cluttered.marble_victorian_bracket"] = "Мраморный викторианский кронштейн"
    tr["block.cluttered.marble_victorian_bracket_scroll"] = "Мраморный кронштейн с завитком"
    tr["block.cluttered.marble_victorian_bracket_bow"] = "Мраморный кронштейн с бантом"
    tr["block.cluttered.marble_victorian_bracket_bow_scroll"] = "Мраморный кронштейн с бантом и завитком"
    tr["block.cluttered.marble_victorian_bracket_star"] = "Мраморный кронштейн со звездой"
    tr["block.cluttered.marble_victorian_bracket_star_scroll"] = "Мраморный кронштейн со звездой и завитком"
    tr["block.cluttered.marble_victorian_bracket_scroll_shelf"] = "Мраморная полка с кронштейном"

    # КОЛИЗЕЙ
    tr["block.cluttered.colosseo_pillar"] = "Колонна Колизея"
    tr["block.cluttered.colosseo_pillar_top"] = "Капитель колонны Колизея"
    tr["block.cluttered.colosseo_pillar_base"] = "База колонны Колизея"
    tr["block.cluttered.colosseo_wall_lantern"] = "Фонарь Колизея"

    # ТЫКВЫ И КОТЫ
    tr["block.cluttered.pumpkin_bookshelf"] = "Книжная полка со светильником Джека"
    tr["block.cluttered.black_cat_window"] = "Окно с чёрным котом"
    tr["block.cluttered.black_cat_window_pane"] = "Оконная рама с чёрным котом"

    # КАШПО ТАРРИ ТАУН (TARREY TOWN)
    tr["block.cluttered.tarrey_town_planter_yellow"] = "Жёлтое кашпо Тарри-Тауна"
    tr["block.cluttered.tarrey_town_planter_pink"] = "Розовое кашпо Тарри-Тауна"
    tr["block.cluttered.tarrey_town_planter_purple"] = "Фиолетовое кашпо Тарри-Тауна"
    tr["block.cluttered.tarrey_town_planter_green"] = "Зелёное кашпо Тарри-Тауна"
    tr["block.cluttered.tarrey_town_planter_fluorescent"] = "Люминесцентное кашпо Тарри-Тауна"
    tr["block.cluttered.tarrey_town_planter_blue"] = "Синее кашпо Тарри-Тауна"
    tr["block.cluttered.tarrey_town_planter_red"] = "Красное кашпо Тарри-Тауна"
    tr["block.cluttered.tarrey_town_planter_beige"] = "Бежевое кашпо Тарри-Тауна"

    # ТКАНИ И X-ПЛИТКА
    tr["block.cluttered.textile_block_stone"] = "Каменный тканевый блок"
    tr["block.cluttered.x_tile_terracotta"] = "Терракотовая X-плитка"
    tr["block.cluttered.x_tile_terracotta_inverse"] = "Инвертированная терракотовая X-плитка"
    tr["block.cluttered.x_tile_blue"] = "Синяя X-плитка"
    tr["block.cluttered.x_tile_blue_inverse"] = "Инвертированная синяя X-плитка"
    tr["block.cluttered.x_tile_gray"] = "Серая X-плитка"
    tr["block.cluttered.x_tile_gray_inverse"] = "Инвертированная серая X-плитка"

    # ДЕРЕВЯННЫЙ ШТАКЕТНИК И КРОНШТЕЙНЫ
    tr["block.cluttered.wooden_picket_fence"] = "Деревянный штакетник"
    tr["block.cluttered.wooden_picket_fence_gate"] = "Калитка из деревянного штакетника"
    tr["block.cluttered.wooden_victorian_bracket"] = "Деревянный викторианский кронштейн"
    tr["block.cluttered.wooden_victorian_bracket_scroll"] = "Деревянный кронштейн с завитком"
    tr["block.cluttered.wooden_victorian_bracket_bow"] = "Деревянный кронштейн с бантом"
    tr["block.cluttered.wooden_victorian_bracket_bow_scroll"] = "Деревянный кронштейн с бантом и завитком"
    tr["block.cluttered.wooden_victorian_bracket_star"] = "Деревянный кронштейн со звездой"
    tr["block.cluttered.wooden_victorian_bracket_star_scroll"] = "Деревянный кронштейн со звездой и завитком"
    tr["block.cluttered.wooden_victorian_bracket_scroll_shelf"] = "Деревянная полка с кронштейном"
    tr["block.cluttered.art_nouveau_door"] = "Дверь в стиле модерн"
    tr["block.cluttered.art_nouveau_door_dark"] = "Тёмная дверь в стиле модерн"

    # ОБОИ
    tr["block.cluttered.starry_wallpaper"] = "Звёздные обои"
    tr["block.cluttered.starry_wallpaper_upper_trim"] = "Звёздные обои (верхний бордюр)"
    tr["block.cluttered.starry_wallpaper_lower_trim"] = "Звёздные обои (нижний бордюр)"
    tr["block.cluttered.dark_starry_wallpaper"] = "Тёмные звёздные обои"
    tr["block.cluttered.dark_starry_wallpaper_upper_trim"] = "Тёмные звёздные обои (верхний бордюр)"
    tr["block.cluttered.dark_starry_wallpaper_lower_trim"] = "Тёмные звёздные обои (нижний бордюр)"
    tr["block.cluttered.retro_rainbow_wallpaper"] = "Ретро-радужные обои"
    tr["block.cluttered.apple_wallpaper"] = "Яблочные обои"
    tr["block.cluttered.blue_rose_striped_wallpaper"] = "Полосатые обои с синими розами"
    tr["block.cluttered.blue_rose_striped_wallpaper_top"] = "Полосатые обои с синими розами (верхний бордюр)"
    tr["block.cluttered.blue_rose_striped_wallpaper_bottom"] = "Полосатые обои с синими розами (нижний бордюр)"
    tr["block.cluttered.checkered_fruit_wallpaper"] = "Клетчатые фруктовые обои"
    tr["block.cluttered.checkered_green_wallpaper"] = "Зелёные клетчатые обои"
    tr["block.cluttered.checkered_pink_wallpaper"] = "Розовые клетчатые обои"
    tr["block.cluttered.checkered_green_strawberry_wallpaper"] = "Зелёные клетчатые обои с земляникой"
    tr["block.cluttered.checkered_pink_strawberry_wallpaper"] = "Розовые клетчатые обои с земляникой"
    tr["block.cluttered.chic_wallpaper"] = "Элегантные обои"
    tr["block.cluttered.chic_wallpaper_upper_trim"] = "Элегантные обои (верхний бордюр)"
    tr["block.cluttered.chic_wallpaper_lower_trim"] = "Элегантные обои (нижний бордюр)"
    tr["block.cluttered.confectionary_wallpaper"] = "Кондитерские обои"
    tr["block.cluttered.confectionary_wallpaper_top"] = "Кондитерские обои (верхний бордюр)"
    tr["block.cluttered.confectionary_wallpaper_bottom"] = "Кондитерские обои (нижний бордюр)"
    tr["block.cluttered.blue_wainscoting"] = "Стеновые панели «Сахарная вата»"
    tr["block.cluttered.floral_berry_wallpaper"] = "Цветочно-ягодные обои"
    tr["block.cluttered.floral_berry_wallpaper_top"] = "Цветочно-ягодные обои (верхний бордюр)"
    tr["block.cluttered.floral_berry_wallpaper_bottom"] = "Цветочно-ягодные обои (нижний бордюр)"
    tr["block.cluttered.floral_border_wallpaper"] = "Обои с цветочным бордюром"
    tr["block.cluttered.ghost_wallpaper"] = "Призрачные обои"
    tr["block.cluttered.ghost_wallpaper_trim"] = "Призрачные обои (бордюр)"
    tr["block.cluttered.ghost_wallpaper_top"] = "Призрачные обои (верхний бордюр)"
    tr["block.cluttered.ghost_wallpaper_bottom"] = "Призрачные обои (нижний бордюр)"
    tr["block.cluttered.ghost_wallpaper_wainscoting"] = "Стеновые панели «Зловещий розовато-лиловый»"
    tr["block.cluttered.tartan_yellow_wallpaper"] = "Жёлтые шотландские обои"
    tr["block.cluttered.fish_wallpaper"] = "Рыбные обои"
    tr["block.cluttered.fish_wallpaper_tropical"] = "Обои с тропическими рыбками"
    tr["block.cluttered.halloween_wallpaper"] = "Хэллоуинские обои"
    tr["block.cluttered.halloween_wallpaper_top"] = "Хэллоуинские обои (верхний бордюр)"
    tr["block.cluttered.halloween_wallpaper_bottom"] = "Хэллоуинские обои (нижний бордюр)"
    tr["block.cluttered.halloween_wainscoting"] = "Стеновые панели «Осенний баклажан»"
    tr["block.cluttered.marigold_wallpaper"] = "Обои с бархатцами"
    tr["block.cluttered.marigold_wallpaper_top"] = "Обои с бархатцами (верхний бордюр)"
    tr["block.cluttered.marigold_wallpaper_bottom"] = "Обои с бархатцами (нижний бордюр)"
    tr["block.cluttered.mint_wallpaper"] = "Мятные обои"
    tr["block.cluttered.mint_wallpaper_top"] = "Мятные обои (верхний бордюр)"
    tr["block.cluttered.mint_wallpaper_bottom"] = "Мятные обои (нижний бордюр)"
    tr["block.cluttered.brown_wainscoting"] = "Стеновые панели «Шоколадная крошка»"
    tr["block.cluttered.pink_striped_wallpaper"] = "Розовые полосатые обои"
    tr["block.cluttered.pink_striped_wallpaper_lower_trim"] = "Розовые полосатые обои (нижний бордюр)"
    tr["block.cluttered.pink_striped_wallpaper_upper_trim"] = "Розовые полосатые обои (верхний бордюр)"
    tr["block.cluttered.rialto_gold_wallpaper"] = "Золотые обои «Риальто»"
    tr["block.cluttered.rialto_wallpaper_upper_trim"] = "Золотые обои «Риальто» (верхний бордюр)"
    tr["block.cluttered.rialto_wallpaper_lower_trim"] = "Золотые обои «Риальто» (нижний бордюр)"
    tr["block.cluttered.striped_floral_wallpaper"] = "Полосатые цветочные обои"
    tr["block.cluttered.striped_floral_wallpaper_top"] = "Полосатые цветочные обои (верхний бордюр)"
    tr["block.cluttered.striped_floral_wallpaper_bottom"] = "Полосатые цветочные обои (нижний бордюр)"

    # DIAMOND MOTIF WALLPAPERS
    motif_names = {
        "apple": "яблочным узором",
        "blackberry": "ежевичным узором",
        "blueberry": "черничным узором",
        "bones": "костяным узором",
        "bouquet": "букетным узором",
        "brown_mushroom": "коричневыми грибами",
        "green_grapes": "зелёным виноградом",
        "lemon": "лимонным узором",
        "orange": "апельсиновым узором",
        "pear": "грушевым узором",
        "plum": "сливовым узором",
        "purple_grapes": "синим виноградом",
        "red_mushroom": "красными мухоморами",
        "strawberry": "земляничным узором",
        "anchor": "якорями"
    }

    for motif_id, motif_ru in motif_names.items():
        base_k = f"block.cluttered.diamond_wallpaper_{motif_id}"
        tr[base_k] = f"Обои с {motif_ru}"
        tr[f"{base_k}_bottom_brown"] = f"Обои с {motif_ru} (коричневый нижний бордюр)"
        tr[f"{base_k}_top_brown"] = f"Обои с {motif_ru} (коричневый верхний бордюр)"
        tr[f"{base_k}_bottom_white"] = f"Обои с {motif_ru} (белый нижний бордюр)"
        tr[f"{base_k}_top_white"] = f"Обои с {motif_ru} (белый верхний бордюр)"
        if f"{base_k}_bottom_color" in en_us:
            tr[f"{base_k}_bottom_color"] = f"Обои с {motif_ru} (цветной нижний бордюр)"
        if f"{base_k}_top_color" in en_us:
            tr[f"{base_k}_top_color"] = f"Обои с {motif_ru} (цветной верхний бордюр)"

    # СТЕНОВЫЕ ПАНЕЛИ ИЗ ДЕРЕВА
    tr["block.cluttered.willow_wainscoting"] = "Ивовые стеновые панели"
    tr["block.cluttered.flowering_willow_wainscoting"] = "Цветущие ивовые стеновые панели"
    tr["block.cluttered.poplar_wainscoting"] = "Тополиные стеновые панели"
    tr["block.cluttered.flowering_poplar_wainscoting"] = "Цветущие тополиные стеновые панели"
    tr["block.cluttered.crabapple_wainscoting"] = "Стеновые панели из дикой яблони"
    tr["block.cluttered.flowering_crabapple_wainscoting"] = "Цветущие стеновые панели из дикой яблони"
    tr["block.cluttered.fluorescent_maple_wainscoting"] = "Стеновые панели из люминесцентного клёна"
    tr["block.cluttered.sycamore_wainscoting"] = "Платановые стеновые панели"
    tr["block.cluttered.blue_mushroom_wainscoting"] = "Стеновые панели из синего гриба"
    tr["block.cluttered.red_mushroom_wainscoting"] = "Стеновые панели из красного гриба"
    tr["block.cluttered.alabaster_wainscoting"] = "Алебастровые стеновые панели"

    # ПРЯНИЧНЫЕ КИРПИЧИ
    tr["block.cluttered.gingerbread_bricks_top_corner"] = "Пряничный угловой карниз"
    tr["block.cluttered.gingerbread_bricks_top"] = "Пряничный верхний карниз"
    tr["block.cluttered.gingerbread_bricks_corner"] = "Пряничный боковой бордюр"
    tr["block.cluttered.gingerbread_bricks"] = "Пряничные кирпичи"
    tr["block.cluttered.gingerbread_brick_stairs"] = "Ступеньки из пряничных кирпичей"
    tr["block.cluttered.gingerbread_brick_slab"] = "Плита из пряничных кирпичей"

    # ДЕКОРАТИВНАЯ ПЛИТКА
    tr["block.cluttered.esperanca_tile"] = "Плитка «Эсперанса»"
    tr["block.cluttered.lily_hills_tile"] = "Плитка «Лили-Хиллз»"
    tr["block.cluttered.hannish_tile"] = "Ханнишская плитка"
    tr["block.cluttered.aura_tiles"] = "Плитка «Аура»"
    tr["block.cluttered.bifurcating_tiles"] = "Разветвлённая плитка"
    tr["block.cluttered.black_amaryllis_tiles"] = "Плитка «Чёрный амариллис»"
    tr["block.cluttered.rosette_tiles"] = "Плитка «Розетка»"
    tr["block.cluttered.seismic_tiles"] = "Сейсмическая плитка"
    tr["block.cluttered.verdant_tile"] = "Зеленеющая плитка"
    tr["block.cluttered.verdant_tile_edge"] = "Край зеленеющей плитки"
    tr["block.cluttered.verdant_tile_corner"] = "Угол зеленеющей плитки"
    tr["block.cluttered.marble_tile"] = "Мраморная напольная плитка"
    tr["block.cluttered.marble_tile_chiseled"] = "Резная мраморная плитка"
    tr["block.cluttered.marble_tile_border"] = "Окаймлённая мраморная плитка"
    tr["block.cluttered.marble_tile_border_circle"] = "Круглая окаймлённая мраморная плитка"
    tr["block.cluttered.marble_tile_border_detailed"] = "Узорная окаймлённая мраморная плитка"
    tr["block.cluttered.marble_tile_corner"] = "Угловая мраморная плитка"
    tr["block.cluttered.marble_tile_corner_circle"] = "Круглая угловая мраморная плитка"
    tr["block.cluttered.tiles_iridescent"] = "Переливчатая плитка"
    tr["block.cluttered.tiles_iridescent_small"] = "Маленькая переливчатая плитка"
    tr["block.cluttered.tiles_green"] = "Зелёная плитка"
    tr["block.cluttered.subway_tiles_green"] = "Зелёная плитка «метро»"
    tr["block.cluttered.tiles_yellow"] = "Жёлтая плитка"
    tr["block.cluttered.subway_tiles_yellow"] = "Жёлтая плитка «метро»"
    tr["block.cluttered.tiles_pink"] = "Розовая плитка"
    tr["block.cluttered.subway_tiles_pink"] = "Розовая плитка «метро»"
    tr["block.cluttered.tiles_purple"] = "Фиолетовая плитка"
    tr["block.cluttered.subway_tiles_purple"] = "Фиолетовая плитка «метро»"

    # БАНКИ С ВАРЕНЬЕМ И ДЖЕМОМ
    tr["block.cluttered.jam_jar_honey"] = "Банка с мёдом"
    tr["block.cluttered.jam_jar_orange"] = "Банка с апельсиновым мармеладом"
    tr["block.cluttered.jam_jar_cherry"] = "Банка с вишнёвым вареньем"
    tr["block.cluttered.jam_jar_strawberry"] = "Банка с клубничным вареньем"
    tr["block.cluttered.jam_jar_apricot"] = "Банка с абрикосовым вареньем"
    tr["block.cluttered.jam_jar_blueberry"] = "Банка с черничным вареньем"

    # АЛЕБАСТРОВЫЕ И ДЕРЕВЯННЫЕ ОКНА, ПАНЕЛИ И ДВЕРИ
    tr["block.cluttered.alabaster_window_divided"] = "Алебастровое окно"
    tr["block.cluttered.alabaster_window_pane"] = "Алебастровая оконная рама"
    tr["block.cluttered.greenhouse_window"] = "Алебастровое оранжерейное окно"
    tr["block.cluttered.greenhouse_window_arch_left"] = "Алебастровое левое арочное окно"
    tr["block.cluttered.greenhouse_window_arch_right"] = "Алебастровое правое арочное окно"
    tr["block.cluttered.greenhouse_window_circle"] = "Алебастровое круглое окно"
    tr["block.cluttered.greenhouse_window_rounded"] = "Алебастровое скруглённое окно"
    tr["block.cluttered.greenhouse_window_pointed"] = "Алебастровое стрельчатое окно"
    tr["block.cluttered.greenhouse_window_radial_left"] = "Алебастровое левое веерное окно"
    tr["block.cluttered.greenhouse_window_radial_right"] = "Алебастровое правое веерное окно"
    tr["block.cluttered.alabaster_screen_door"] = "Алебастровая сетчатая дверь"
    tr["block.cluttered.alabaster_french_door"] = "Алебастровая французская дверь"
    tr["block.cluttered.wooden_window_divided"] = "Деревянное окно"
    tr["block.cluttered.wooden_window_pane"] = "Деревянная оконная рама"
    tr["block.cluttered.wooden_canterbury_panel"] = "Деревянная панель «Кентербери»"
    tr["block.cluttered.wooden_atlantic_panel"] = "Деревянная панель «Атлантика»"
    tr["block.cluttered.wooden_alexandria_panel"] = "Деревянная панель «Александрия»"
    tr["block.cluttered.wooden_augustine_panel"] = "Деревянная панель «Августин»"
    tr["block.cluttered.wooden_screen_door"] = "Деревянная сетчатая дверь"
    tr["block.cluttered.wooden_french_door"] = "Деревянная французская дверь"
    tr["block.cluttered.wicker_block"] = "Плетёный блок"
    tr["block.cluttered.chiseled_gold_block"] = "Резной золотой блок"
    tr["block.cluttered.antique_bricks"] = "Старинные кирпичи"
    tr["block.cluttered.antique_bricks_border"] = "Окаймлённые старинные кирпичи"
    tr["block.cluttered.dynasty_door"] = "Дверь династии"
    tr["block.cluttered.eye_block"] = "Смотрящий блок"
    tr["block.cluttered.apple_chair"] = "Яблочный стул"

    # СКВОРЕЧНИКИ
    tr["block.cluttered.birdhouse_red"] = "Красный скворечник"
    tr["block.cluttered.birdhouse_blue"] = "Синий скворечник"
    tr["block.cluttered.birdhouse_pastel"] = "Пастельный скворечник"
    tr["block.cluttered.birdhouse_unpainted"] = "Деревянный скворечник"

    # ЧЕМОДАНЫ, ДЕКОР, КРАСКИ, КОРОБКИ, КРУЖКИ
    tr["block.cluttered.briefcase_blank"] = "Чемодан"
    tr["block.cluttered.briefcase_rover"] = "Чемодан бродяги"
    tr["block.cluttered.bunny_book_ends"] = "Подставки для книг с зайчиками"
    tr["block.cluttered.box_of_paints"] = "Набор красок"
    tr["block.cluttered.button_stool"] = "Табурет-пуговица"
    tr["block.cluttered.cardboard_box_open"] = "Картонная коробка"
    tr["block.cluttered.cat_mugs_cluttered"] = "Кружки с котиками"
    tr["block.cluttered.cat_plant_pot_black"] = "Цветочный горшок «Чёрный кот»"
    tr["block.cluttered.cat_plant_pot_orange"] = "Цветочный горшок «Рыжий кот»"
    tr["block.cluttered.coffee_grinder"] = "Кофемолка"
    tr["block.cluttered.cauldron_poster"] = "Плакат с котлом"
    tr["block.cluttered.spool_of_thread_yellow"] = "Жёлтая катушка ниток"
    tr["block.cluttered.spool_of_thread_green"] = "Зелёная катушка ниток"
    tr["block.cluttered.spool_of_thread_purple"] = "Фиолетовая катушка ниток"
    tr["block.cluttered.spool_of_thread_pink"] = "Розовая катушка ниток"
    tr["block.cluttered.analog_kitchen_scale"] = "Кухонные весы"
    tr["block.cluttered.antique_map"] = "Старинная карта"
    tr["block.cluttered.antique_mini_table"] = "Старинный мини-столик"
    tr["block.cluttered.ancient_codex"] = "Древний кодекс"
    tr["block.cluttered.antique_book_stand"] = "Старинная подставка для книг"
    tr["block.cluttered.antique_library_books"] = "Старинные библиотечные книги"
    tr["block.cluttered.bee_lamp"] = "Лампа-пчёлка"
    tr["block.cluttered.bee_lamp_angry"] = "Сердитая лампа-пчёлка"

    # ПРОИГРЫВАТЕЛИ ПЛАСТИНОК
    tr["block.cluttered.record_player_red"] = "Красный виниловый проигрыватель"
    tr["block.cluttered.record_player_yellow"] = "Жёлтый виниловый проигрыватель"
    tr["block.cluttered.record_player_blue"] = "Синий виниловый проигрыватель"
    tr["block.cluttered.record_player_purple"] = "Фиолетовый виниловый проигрыватель"
    tr["block.cluttered.record_player_pink"] = "Розовый виниловый проигрыватель"
    tr["block.cluttered.record_player_brown"] = "Коричневый виниловый проигрыватель"
    tr["block.cluttered.record_player_white"] = "Белый виниловый проигрыватель"

    # ВЕЛОСИПЕДЫ
    tr["block.cluttered.bicycle_yellow"] = "Жёлтый велосипед"
    tr["block.cluttered.bicycle_with_flowers_yellow"] = "Жёлтый велосипед с цветами"
    tr["block.cluttered.bicycle_blue"] = "Синий велосипед"
    tr["block.cluttered.bicycle_with_flowers_blue"] = "Синий велосипед с цветами"
    tr["block.cluttered.bicycle_purple"] = "Фиолетовый велосипед"
    tr["block.cluttered.bicycle_with_flowers_purple"] = "Фиолетовый велосипед с цветами"
    tr["block.cluttered.bicycle_pink"] = "Розовый велосипед"
    tr["block.cluttered.bicycle_with_flowers_pink"] = "Розовый велосипед с цветами"

    # МЕБЕЛЬ ДЛЯ КОТТЕДЖА
    tr["block.cluttered.cottage_side_table"] = "Прикроватный столик для коттеджа"
    tr["block.cluttered.cottage_chair"] = "Стул для коттеджа"
    tr["block.cluttered.cottage_chair_cushioned"] = "Мягкий стул для коттеджа"
    tr["block.cluttered.cottage_ottoman"] = "Пуфик для коттеджа"
    tr["block.cluttered.cottage_bookcase"] = "Книжный шкаф для коттеджа"
    tr["block.cluttered.cottage_standing_lamp"] = "Торшер для коттеджа"
    tr["block.cluttered.cottage_armchair"] = "Кресло для коттеджа"

    # АВТОМАТЫ С ЖВАЧКОЙ
    tr["block.cluttered.gumball_machine_red"] = "Красный автомат с жвачкой"
    tr["block.cluttered.gumball_machine_blue"] = "Синий автомат с жвачкой"
    tr["block.cluttered.gumball_machine_purple"] = "Фиолетовый автомат с жвачкой"

    # ДЕКОР, РАСТЕНИЯ, ТЕРРАРИУМЫ, БУМАГА
    tr["block.cluttered.mini_cactus_set"] = "Набор мини-кактусов"
    tr["block.cluttered.newspaper_pile_short"] = "Стопка газет"
    tr["block.cluttered.newspaper_pile_tall"] = "Высокая стопка газет"
    tr["block.cluttered.paper_pile"] = "Стопка бумаг"
    tr["block.cluttered.glowshroom_terrarium_yellow"] = "Жёлтый террариум со светящимся грибом"
    tr["block.cluttered.glowshroom_terrarium_green"] = "Зелёный террариум со светящимся грибом"
    tr["block.cluttered.glowshroom_terrarium_blue"] = "Синий террариум со светящимся грибом"
    tr["block.cluttered.glowshroom_terrarium_purple"] = "Фиолетовый террариум со светящимся грибом"
    tr["block.cluttered.glowshroom_terrarium_pink"] = "Розовый террариум со светящимся грибом"
    tr["block.cluttered.fence_shelf_blue"] = "Полка на забор"
    tr["block.cluttered.hanging_plant_pot_flowers"] = "Подвесной горшок с цветами"
    tr["block.cluttered.hanging_plant_pot_grass"] = "Подвесной горшок с травой"
    tr["block.cluttered.pedestal_hk"] = "Пьедестал Хелло Китти"
    tr["block.cluttered.picnic_basket"] = "Корзина для пикника"
    tr["block.cluttered.picnic_basket_prepared"] = "Собранная корзина для пикника"
    tr["block.cluttered.basket_of_produce"] = "Корзина с продуктами"
    tr["block.cluttered.basket_of_flowers"] = "Корзина с цветами"
    tr["block.cluttered.polaroids_a"] = "Снимки полароида A"
    tr["block.cluttered.polaroids_b"] = "Снимки полароида B"
    tr["block.cluttered.polaroids_c"] = "Снимки полароида C"

    # ПОДВЕСНЫЕ ЛАМПЫ OSSON
    tr["block.cluttered.osson_pendant_black"] = "Чёрная подвесная лампа"
    tr["block.cluttered.osson_pendant_brown"] = "Коричневая подвесная лампа"
    tr["block.cluttered.osson_pendant_orange"] = "Оранжевая подвесная лампа"
    tr["block.cluttered.osson_pendant_racing_green"] = "Зелёная подвесная лампа"
    tr["block.cluttered.osson_pendant_sage_green"] = "Лаймовая подвесная лампа"
    tr["block.cluttered.osson_pendant_red"] = "Красная подвесная лампа"
    tr["block.cluttered.osson_pendant_yellow"] = "Жёлтая подвесная лампа"
    tr["block.cluttered.osson_pendant_white"] = "Белая подвесная лампа"

    # СУШЁНЫЕ ТРАВЫ, ТКАНИ, ТОРТЫ
    tr["block.cluttered.drying_herbs"] = "Сушащиеся травы"
    tr["block.cluttered.hanging_cloth"] = "Висящая ткань"
    tr["block.cluttered.heart_cake"] = "Торт в форме сердца"
    tr["block.cluttered.berry_cake"] = "Ягодный торт"

    # МИНИ-ФЛАЖКИ И АНИМИРОВАННЫЕ ФЛАГИ
    tr["block.cluttered.mini_flag_rainbow"] = "Миниатюрный радужный флаг"
    tr["block.cluttered.mini_flag_lesbian"] = "Миниатюрный лесби-флаг"
    tr["block.cluttered.mini_flag_bi"] = "Миниатюрный би-флаг"
    tr["block.cluttered.mini_flag_pan"] = "Миниатюрный пан-флаг"
    tr["block.cluttered.mini_flag_ace"] = "Миниатюрный асе-флаг"
    tr["block.cluttered.mini_flag_trans"] = "Миниатюрный транс-флаг"
    tr["block.cluttered.mini_flag_nonbinary"] = "Миниатюрный небинарный флаг"
    tr["block.cluttered.animated_flag_rainbow"] = "Радужный флаг"
    tr["block.cluttered.animated_flag_lesbian"] = "Лесби-флаг"
    tr["block.cluttered.animated_flag_bisexual"] = "Би-флаг"
    tr["block.cluttered.animated_flag_pansexual"] = "Пан-флаг"
    tr["block.cluttered.animated_flag_asexual"] = "Асе-флаг"
    tr["block.cluttered.animated_flag_transgender"] = "Транс-флаг"
    tr["block.cluttered.animated_flag_nonbinary"] = "Небинарный флаг"

    # ПОЛКИ И ШКАФЫ
    tr["block.cluttered.bamboo_bookshelf"] = "Бамбуковая книжная полка"
    tr["block.cluttered.fwish_bookcase"] = "Книжный шкаф «Фвиш»"
    tr["block.cluttered.retro_cafe_shelf"] = "Полка для ретро-кафе"
    tr["block.cluttered.retro_cafe_shelf_window"] = "Оконная полка для ретро-кафе"
    tr["block.cluttered.potion_shelf"] = "Полка с зельями"
    tr["block.cluttered.china_cabinet"] = "Буфет для посуды"
    tr["block.cluttered.cupid_bench"] = "Скамья Купидона"

    # СТОЛИКИ И ТУМБЫ ENDTABLE
    tr["block.cluttered.endtable_amethyst"] = "Аметистовый приставной столик"
    tr["block.cluttered.endtable_charcoal"] = "Угольный приставной столик"
    tr["block.cluttered.endtable_meadow"] = "Луговой приставной столик"
    tr["block.cluttered.endtable_periwinkle"] = "Барвинковый приставной столик"
    tr["block.cluttered.endtable_sunshine"] = "Солнечный приставной столик"
    tr["block.cluttered.endtable_wood"] = "Деревянный приставной столик"
    tr["block.cluttered.endtable_bubblegum"] = "Конфетный приставной столик"
    tr["block.cluttered.endtable_decor"] = "Декор для приставного столика"
    tr["block.cluttered.nightstand_green"] = "Зелёная тумбочка"
    tr["block.cluttered.desk_green"] = "Зелёный письменный стол"
    tr["block.cluttered.desk_green_cluttered"] = "Захламлённый зелёный письменный стол"
    tr["block.cluttered.desk_brown"] = "Коричневый письменный стол"
    tr["block.cluttered.desk_brown_cluttered"] = "Захламлённый коричневый письменный стол"
    tr["block.cluttered.rover_stool"] = "Табурет бродяги"
    tr["block.cluttered.madonna_ottoman"] = "Пуфик «Мадонна»"
    tr["block.cluttered.rubiks_cube"] = "Кубик Рубика"
    tr["block.cluttered.rubiks_cube_pastel"] = "Пастельный кубик Рубика"
    tr["block.cluttered.row_of_small_books"] = "Ряд маленьких книг"
    tr["block.cluttered.row_of_small_books_pastel"] = "Ряд маленьких пастельных книг"
    tr["block.cluttered.scattered_papers"] = "Разбросанные бумаги"
    tr["block.cluttered.row_of_small_books_shelved"] = "Полка с книгами"
    tr["block.cluttered.row_of_small_books_pastel_shelved"] = "Полка с пастельными книгами"
    tr["block.cluttered.stained_glass_lamp"] = "Витражная лампа"
    tr["block.cluttered.small_bush"] = "Маленький кустик"
    tr["block.cluttered.teddy_bear"] = "Плюшевый мишка"
    tr["block.cluttered.small_shelf"] = "Маленькая полка"
    tr["block.cluttered.small_shelf_pink"] = "Маленькая розовая полка"
    tr["block.cluttered.two_flower_pots"] = "Два цветочных горшка"
    tr["block.cluttered.traditional_radio"] = "Традиционный радиоприёмник"
    tr["block.cluttered.sewing_mannequin"] = "Портновский манекен"
    tr["block.cluttered.sewing_machine_antique"] = "Старинная швейная машинка"
    tr["block.cluttered.watering_can"] = "Лейка"
    tr["block.cluttered.watering_can_copper"] = "Медная лейка"
    tr["block.cluttered.stars_pendant"] = "Подвеска со звёздами"
    tr["block.cluttered.moon_pendant"] = "Подвеска с луной"
    tr["block.cluttered.moon_decoration"] = "Настенное украшение «Луна»"
    tr["block.cluttered.caged_bulb"] = "Лампочка в решётке"
    tr["block.cluttered.antique_standing_lamp"] = "Старинный торшер"
    tr["block.cluttered.bulletin_board"] = "Доска объявлений"
    tr["block.cluttered.bulletin_board_cluttered"] = "Завешанная доска объявлений"
    tr["block.cluttered.lovely_love_seat_basic"] = "Милый двухместный диванчик"
    tr["block.cluttered.lovely_love_seat_black"] = "Чёрный милый двухместный диванчик"

    # ГИРЛЯНДЫ
    tr["block.cluttered.garland_black_cat"] = "Гирлянда с чёрными котиками"
    tr["block.cluttered.garland_blossom"] = "Цветочная гирлянда"
    tr["block.cluttered.garland_bunny"] = "Гирлянда с зайчиками"
    tr["block.cluttered.garland_polaroid_a"] = "Гирлянда со снимками полароида A"
    tr["block.cluttered.garland_polaroid_b"] = "Гирлянда со снимками полароида B"
    tr["block.cluttered.garland_sunflower"] = "Гирлянда с подсолнухами"
    tr["block.cluttered.garland_starry"] = "Звёздная гирлянда"

    # КРЕСЛА
    tr["block.cluttered.armchair_white"] = "Белое кресло"
    tr["block.cluttered.armchair_light_gray"] = "Светло-серое кресло"
    tr["block.cluttered.armchair_gray"] = "Серое кресло"
    tr["block.cluttered.armchair_black"] = "Чёрное кресло"
    tr["block.cluttered.armchair_brown"] = "Коричневое кресло"
    tr["block.cluttered.armchair_red"] = "Красное кресло"
    tr["block.cluttered.armchair_orange"] = "Оранжевое кресло"
    tr["block.cluttered.armchair_yellow"] = "Жёлтое кресло"
    tr["block.cluttered.armchair_lime"] = "Лаймовое кресло"
    tr["block.cluttered.armchair_green"] = "Зелёное кресло"
    tr["block.cluttered.armchair_cyan"] = "Бирюзовое кресло"
    tr["block.cluttered.armchair_light_blue"] = "Светло-синее кресло"
    tr["block.cluttered.armchair_blue"] = "Синее кресло"
    tr["block.cluttered.armchair_purple"] = "Фиолетовое кресло"
    tr["block.cluttered.armchair_magenta"] = "Пурпурное кресло"
    tr["block.cluttered.armchair_pink"] = "Розовое кресло"
    tr["block.cluttered.armchair_fuchsia"] = "Кресло цвета фуксии"
    tr["block.cluttered.armchair_ivory"] = "Кресло цвета слоновой кости"
    tr["block.cluttered.armchair_flower"] = "Цветочное кресло"
    tr["block.cluttered.armchair_strawberry"] = "Земляничное кресло"
    tr["block.cluttered.armchair_watermelon"] = "Арбузное кресло"
    tr["block.cluttered.armchair_lemon"] = "Лимонное кресло"
    tr["block.cluttered.armchair_heart"] = "Кресло с сердечком"
    tr["block.cluttered.armchair_starry"] = "Звёздное кресло"
    tr["block.cluttered.armchair_black_cat"] = "Кресло с чёрным котом"

    # МЕБЕЛЬ ИЗ ТЁМНОГО ДЕРЕВА (DARKWOOD)
    tr["block.cluttered.darkwood_chair_geometric"] = "Кресло из тёмного дерева (геометрия)"
    tr["block.cluttered.darkwood_chair_quilted"] = "Кресло из тёмного дерева (стёганое)"
    tr["block.cluttered.darkwood_chair_southern_flair"] = "Кресло из тёмного дерева (южный стиль)"
    tr["block.cluttered.darkwood_sofa_geometric"] = "Диван из тёмного дерева (геометрия)"
    tr["block.cluttered.darkwood_sofa_quilted"] = "Диван из тёмного дерева (стёганый)"
    tr["block.cluttered.darkwood_sofa_southern_flair"] = "Диван из тёмного дерева (южный стиль)"
    tr["block.cluttered.darkwood_decorative_shelves_geometric"] = "Полка из тёмного дерева (геометрия)"
    tr["block.cluttered.darkwood_decorative_shelves_quilted"] = "Полка из тёмного дерева (стёганая)"
    tr["block.cluttered.darkwood_decorative_shelves_southern_flair"] = "Полка из тёмного дерева (южный стиль)"
    tr["block.cluttered.darkwood_endtable"] = "Приставной столик из тёмного дерева"
    tr["block.cluttered.darkwood_table"] = "Стол из тёмного дерева"
    tr["block.cluttered.darkwood_stool"] = "Табурет из тёмного дерева"
    tr["block.cluttered.darkwood_cabinet"] = "Шкаф из тёмного дерева"
    tr["block.cluttered.darkwood_clock"] = "Часы из тёмного дерева"
    tr["block.cluttered.darkwood_bed_geometric"] = "Кровать из тёмного дерева (геометрия)"
    tr["block.cluttered.darkwood_bed_quilted"] = "Кровать из тёмного дерева (стёганая)"
    tr["block.cluttered.darkwood_bed_southern_flair"] = "Кровать из тёмного дерева (южный стиль)"

    # СТОЛЫ И ШКАФЫ
    tr["block.cluttered.table"] = "Стол"
    tr["block.cluttered.flower_tea_kettle"] = "Цветочный заварочный чайник"
    tr["block.cluttered.table_with_white_tablecloth"] = "Стол со скатертью"
    tr["block.cluttered.dorado_cabinet"] = "Шкаф «Дорадо»"
    tr["block.cluttered.dorado_cabinet_cluttered"] = "Заполненный шкаф «Дорадо»"
    tr["block.cluttered.havana_cabinet"] = "Шкаф «Гавана»"
    tr["block.cluttered.havana_cabinet_cluttered"] = "Заполненный шкаф «Гавана»"
    tr["block.cluttered.murex_cabinet"] = "Шкаф «Мурекс»"
    tr["block.cluttered.murex_cabinet_cluttered"] = "Заполненный шкаф «Мурекс»"

    # МОДУЛЬНЫЕ КУХОННЫЕ ГАРНИТУРЫ (KITCHEN SETS)
    kitchen_colors = {
        "brown": "Коричневая",
        "light_green": "Лаймовая",
        "pink": "Розовая",
        "purple": "Фиолетовая",
        "white": "Белая",
        "yellow": "Жёлтая"
    }

    for col_id, col_name in kitchen_colors.items():
        tr[f"block.cluttered.kitchen_set_{col_id}_counter"] = f"{col_name} кухонная тумба"
        tr[f"block.cluttered.kitchen_set_{col_id}_counter_inner_corner"] = f"{col_name} внутренняя угловая тумба"
        tr[f"block.cluttered.kitchen_set_{col_id}_counter_outer_corner_right"] = f"{col_name} правая внешняя угловая тумба"
        tr[f"block.cluttered.kitchen_set_{col_id}_counter_outer_corner_left"] = f"{col_name} левая внешняя угловая тумба"
        tr[f"block.cluttered.kitchen_set_{col_id}_counter_sink"] = f"{col_name} кухонная тумба с раковиной"
        tr[f"block.cluttered.kitchen_set_{col_id}_cabinet"] = f"{col_name} навесной шкафчик"
        tr[f"block.cluttered.kitchen_set_{col_id}_cabinet_mini"] = f"{col_name} маленький навесной шкафчик"
        tr[f"block.cluttered.kitchen_set_{col_id}_cabinet_glass"] = f"{col_name} остеклённый навесной шкафчик"
        tr[f"block.cluttered.kitchen_set_{col_id}_cabinet_open"] = f"{col_name} открытый навесной шкафчик"
        tr[f"block.cluttered.kitchen_set_{col_id}_cabinet_inner_corner"] = f"{col_name} внутренний угловой шкафчик"
        tr[f"block.cluttered.kitchen_set_{col_id}_cabinet_outer_corner"] = f"{col_name} внешний угловой шкафчик"

    # ГАРНИТУРЫ С ЧЁРНЫМ КОТОМ И SWEETHEART
    tr["block.cluttered.black_cat_counter_drawers"] = "Кухонная тумба «Чёрный кот» с ящиками"
    tr["block.cluttered.black_cat_counter_left_door"] = "Левая кухонная тумба «Чёрный кот»"
    tr["block.cluttered.black_cat_counter_right_door"] = "Правая кухонная тумба «Чёрный кот»"
    tr["block.cluttered.black_cat_sink"] = "Раковина «Чёрный кот»"
    tr["block.cluttered.black_cat_table"] = "Стол «Чёрный кот»"

    tr["block.cluttered.sweetheart_counter_drawers"] = "Милая кухонная тумба с ящиками"
    tr["block.cluttered.sweetheart_counter_left_door"] = "Левая милая кухонная тумба"
    tr["block.cluttered.sweetheart_counter_right_door"] = "Правая милая кухонная тумба"
    tr["block.cluttered.sweetheart_sink"] = "Милая раковина"
    tr["block.cluttered.sweetheart_table"] = "Милый стол"
    tr["block.cluttered.sweetheart_baking_set_bowl"] = "Миска для смешивания"
    tr["block.cluttered.sweetheart_baking_set_ingredients"] = "Ингредиенты для выпечки"
    tr["block.cluttered.confectionery_table_blue"] = "Синий кондитерский стол"
    tr["block.cluttered.confectionery_table_pink"] = "Розовый кондитерский стол"

    # МЕЛОЧИ ДЛЯ ДОМА
    tr["block.cluttered.jam_jars"] = "Баночки с вареньем"
    tr["block.cluttered.book_open"] = "Раскрытая книга"
    tr["block.cluttered.brass_key"] = "Латунный ключ"
    tr["block.cluttered.card_index"] = "Картотека"
    tr["block.cluttered.envelope_stack"] = "Стопка конвертов"
    tr["block.cluttered.flower_desk_lamp"] = "Цветочная настольная лампа"

    # ЦВЕТОЧНЫЕ ПОЛОЧКИ И СВЕЧИ
    tr["block.cluttered.flower_shelf_blue"] = "Синяя цветочная полка"
    tr["block.cluttered.flower_shelf_pastel_yellow"] = "Пастельно-жёлтая цветочная полка"
    tr["block.cluttered.flower_shelf_pink"] = "Розовая цветочная полка"
    tr["block.cluttered.flower_shelf_purple"] = "Фиолетовая цветочная полка"
    tr["block.cluttered.flower_shelf_yellow"] = "Жёлтая цветочная полка"
    tr["block.cluttered.flower_shelf_green"] = "Зелёная цветочная полка"
    tr["block.cluttered.flower_shelf_candle_blue"] = "Синяя свеча для цветочной полки"
    tr["block.cluttered.flower_shelf_candle_pastel_yellow"] = "Пастельно-жёлтая свеча для цветочной полки"
    tr["block.cluttered.flower_shelf_candle_pink"] = "Розовая свеча для цветочной полки"
    tr["block.cluttered.flower_shelf_candle_purple"] = "Фиолетовая свеча для цветочной полки"
    tr["block.cluttered.flower_shelf_candle_yellow"] = "Жёлтая свеча для цветочной полки"
    tr["block.cluttered.flower_shelf_candle_green"] = "Зелёная свеча для цветочной полки"
    tr["block.cluttered.flower_shelf_plant"] = "Растение для цветочной полки"

    # МЕБЕЛЬ FWISH И ОБЩИЕ ШКАФЫ
    tr["block.cluttered.fwish_armchair"] = "Кресло «Фвиш»"
    tr["block.cluttered.fwish_ottoman"] = "Пуфик «Фвиш»"
    tr["block.cluttered.general_store_cabinet"] = "Шкаф из сельской лавки"
    tr["block.cluttered.heavenly_ornamental_array"] = "Небесная декоративная композиция"
    tr["block.cluttered.plant_ladder"] = "Подставка-лестница для растений"
    tr["block.cluttered.polaroid_camera"] = "Камера Polaroid"

    # СТОЛИКИ-ПАЗЛЫ
    tr["block.cluttered.puzzle_piece_table_blue"] = "Синий столик-пазл"
    tr["block.cluttered.puzzle_piece_table_green"] = "Зелёный столик-пазл"
    tr["block.cluttered.puzzle_piece_table_red"] = "Красный столик-пазл"
    tr["block.cluttered.puzzle_piece_table_yellow"] = "Жёлтый столик-пазл"
    tr["block.cluttered.puzzle_piece_table_pastel_blue"] = "Пастельно-синий столик-пазл"
    tr["block.cluttered.puzzle_piece_table_pastel_pink"] = "Пастельно-розовый столик-пазл"
    tr["block.cluttered.puzzle_piece_table_pastel_purple"] = "Пастельно-фиолетовый столик-пазл"
    tr["block.cluttered.puzzle_piece_table_pastel_yellow"] = "Пастельно-жёлтый столик-пазл"

    # РЕТРО-ХОЛОДИЛЬНИКИ И ТОСТЕРЫ
    retro_colors = {
        "black": ("Чёрный", "Чёрный"),
        "blue": ("Синий", "Синий"),
        "pink": ("Розовый", "Розовый"),
        "purple": ("Фиолетовый", "Фиолетовый"),
        "red": ("Красный", "Красный"),
        "turquoise": ("Бирюзовый", "Бирюзовый"),
        "white": ("Белый", "Белый"),
        "yellow": ("Жёлтый", "Жёлтый")
    }

    for col_id, (adj_m, adj_t) in retro_colors.items():
        tr[f"block.cluttered.retro_fridge_{col_id}"] = f"{adj_m} ретро-холодильник"
        tr[f"block.cluttered.retro_toaster_{col_id}"] = f"{adj_t} ретро-тостер"

    # КУХНЯ, ТКАНИ, ПЛЮШЕВЫЕ ИГРУШКИ, КНИГИ
    tr["block.cluttered.salt_pepper_shakers"] = "Солонка и перечница"
    tr["block.cluttered.fabric_bolts"] = "Рулоны ткани"
    tr["block.cluttered.sand_seal_plush_blue"] = "Синий плюшевый песчаный котик"
    tr["block.cluttered.sand_seal_plush_red"] = "Красный плюшевый песчаный котик"
    tr["block.cluttered.sand_seal_plush_green"] = "Зелёный плюшевый песчаный котик"
    tr["block.cluttered.sketchbook_single"] = "Скетчбук"
    tr["block.cluttered.stack_of_books"] = "Стопка книг"
    tr["block.cluttered.stack_of_books_tall"] = "Высокая стопка книг"
    tr["block.cluttered.steampunk_globe"] = "Стимпанк-глобус"
    tr["block.cluttered.wine_bottle_rack"] = "Винная полка"
    tr["block.cluttered.wine_bottles"] = "Бутылки вина"
    tr["block.cluttered.yellow_notepad"] = "Блокнот"
    tr["block.cluttered.scissors_and_thread"] = "Ножницы и нитки"
    tr["block.cluttered.sliced_bread"] = "Нарезанный хлеб"
    tr["block.cluttered.rose_end_table"] = "Приставной столик «Роза»"
    tr["block.cluttered.rose_end_table_black"] = "Чёрный приставной столик «Роза»"
    tr["block.cluttered.vial_stand"] = "Подставка для пробирок"
    tr["block.cluttered.pineapple"] = "Декоративный ананас"
    tr["block.cluttered.honeycomb_lamp"] = "Лампа «Соты»"
    tr["block.cluttered.unliving_chair"] = "Неживой стул"
    tr["block.cluttered.safe_novakid"] = "Сейф новакида"
    tr["block.cluttered.hoppin_park_lantern"] = "Парковый фонарь «Хоппин»"
    tr["block.cluttered.sea_gem_lantern"] = "Фонарь из морского самоцвета"
    tr["block.cluttered.violet_screen"] = "Фиолетовая ширма"
    tr["block.cluttered.hanging_shelves_pottery"] = "Подвесные полки с керамикой"
    tr["block.cluttered.hanging_shelves_plants"] = "Подвесные полки с растениями"
    tr["block.cluttered.pok_ta_pok_hoop"] = "Кольцо для пок-та-пок"
    tr["block.cluttered.pok_ta_pok_hoop_snakes"] = "Кольцо со змеями для пок-та-пок"

    # ВЫПЕЧКА И ЕДА
    tr["block.cluttered.pastry_plate"] = "Тарелка со сладостями"
    tr["block.cluttered.chocolate_croissant"] = "Шоколадный круассан"
    tr["block.cluttered.croissant"] = "Круассан"
    tr["block.cluttered.blueberry_muffin"] = "Черничный маффин"
    tr["block.cluttered.cinnamon_bun"] = "Булочка с корицей"
    tr["block.cluttered.pancake_stack"] = "Стопка блинчиков"
    tr["block.cluttered.ham_sandwich"] = "Сэндвич с ветчиной"

    # ШИТЬЁ, ВАЗЫ, ПРЕДМЕТЫ ИНТЕРЬЕРА
    tr["block.cluttered.sewing_table_with_tablecloth"] = "Швейный столик со скатертью"
    tr["block.cluttered.sewing_clutter"] = "Швейные принадлежности"
    tr["block.cluttered.glass_vase_of_flowers"] = "Стеклянная ваза с цветами"
    tr["block.cluttered.paint_water_jar"] = "Баночка с водой для рисования"
    tr["block.cluttered.mermaid_pearl"] = "Жемчужина русалки"
    tr["block.cluttered.imperial_chair"] = "Имперский стул"
    tr["block.cluttered.imperial_table"] = "Имперский стол"

    # ЛУННАЯ ОБСЕРВАТОРИЯ
    tr["block.cluttered.lunar_observatory_table"] = "Стол лунной обсерватории"
    tr["block.cluttered.lunar_observatory_pedestal_table"] = "Круглый столик лунной обсерватории"
    tr["block.cluttered.lunar_observatory_books"] = "Книги лунной обсерватории"
    tr["block.cluttered.lunar_observatory_basket_of_papers"] = "Корзина для бумаг лунной обсерватории"
    tr["block.cluttered.lunar_observatory_globe"] = "Глобус лунной обсерватории"
    tr["block.cluttered.lunar_observatory_jar"] = "Банки лунной обсерватории"

    # СТЕКЛЯННЫЕ БАНОЧКИ И ВИТРИНЫ
    tr["block.cluttered.assorted_glass_jars"] = "Набор стеклянных баночек"
    tr["block.cluttered.small_glass_jars"] = "Маленькие стеклянные баночки"
    tr["block.cluttered.small_spice_jars"] = "Баночки для специй"
    tr["block.cluttered.pastry_display_course"] = "Витрина для выпечки"
    tr["block.cluttered.lemon_table"] = "Лимонный столик"
    tr["block.cluttered.mermaid_dresser"] = "Комод русалки"
    tr["block.cluttered.rover_mug"] = "Кружка бродяги"

    # ПАСТЕЛЬНЫЙ НАБОР МЕБЕЛИ
    tr["block.cluttered.pastel_chair"] = "Пастельный стул"
    tr["block.cluttered.pastel_stool"] = "Пастельный табурет"
    tr["block.cluttered.pastel_table"] = "Пастельный стол"
    tr["block.cluttered.pastel_light"] = "Пастельный светильник"
    tr["block.cluttered.pastel_cabinet"] = "Пастельный шкафчик"
    tr["block.cluttered.pastel_wardrobe"] = "Пастельный гардероб"
    tr["block.cluttered.pastel_bed"] = "Пастельная кровать"
    tr["block.cluttered.pastel_bunny_plushie"] = "Пастельный плюшевый зайчик"

    # СТИМПАНК, СВАДЬБА, ОФИС И ДРУГОЕ
    tr["block.cluttered.steampunk_lamp"] = "Стимпанк-лампа"
    tr["block.cluttered.wedding_arch"] = "Свадебная арка"
    tr["block.cluttered.mini_hanging_terrariums"] = "Миниатюрные подвесные террариумы"
    tr["block.cluttered.small_bookcase"] = "Маленький книжный шкаф"
    tr["block.cluttered.rito_wooden_books"] = "Деревянные книги рито"
    tr["block.cluttered.office_supplies_a"] = "Канцелярские принадлежности A"
    tr["block.cluttered.office_supplies_b"] = "Канцелярские принадлежности B"
    tr["block.cluttered.filing_box"] = "Коробка для документов"
    tr["block.cluttered.small_cauldron_set"] = "Набор маленьких котлов"
    tr["block.cluttered.tarrytown_stove"] = "Плита Тарри-Тауна"
    tr["block.cluttered.seltzer_cans"] = "Баночки сельтерской воды"
    tr["block.cluttered.pastry_display_case"] = "Витрина для выпечки"
    tr["block.cluttered.wooden_block_bookshelf_pastel"] = "Пастельная деревянная книжная полка"
    tr["block.cluttered.seaweed_planter"] = "Кашпо с морскими водорослями"

    return en_us, tr

if __name__ == "__main__":
    en_us, tr = build_all_translations()
    print(f"Total keys in en_us: {len(en_us)}")
    print(f"Total translated keys: {len(tr)}")
    missing = [k for k in en_us if k not in tr]
    print(f"Missing keys: {len(missing)}")
    if missing:
        for m in missing[:20]:
            print(f"Missing: {m} -> {en_us[m]}")
