const fs = require('fs');
const path = require('path');

const tipsRu = {
  "society_tips.tip.mining_skill_fortune": "Если в начале игры вам не по карману чары «Удача», вложите очки в узлы Удачи в древе навыка Горного дела.",
  "society_tips.tip.slot_machine": "Использование монеты в игровом автомате принесёт в 3 раза больше в случае выигрыша!",
  "society_tips.tip.auto_trader": "Авто-торговец способен автоматизировать покупки и сделки в лавках.",
  "society_tips.tip.fire_quartz_one": "Огненный кварц можно найти в Незере и в горячих биомах Пещеры Черепа.",
  "society_tips.tip.earth_crystals_one": "Кристаллы земли встречаются в обычном мире и в некоторых биомах Пещеры Черепа.",
  "society_tips.tip.gold_slimes": "Золотые слизни крадут деньги с вашего банковского счёта, когда раздражены.",
  "society_tips.tip.nether_vacation": "Незер — прекрасное место для проведения отпуска!",
  "society_tips.tip.pig_racing": "Это же свиные бега!",
  "society_tips.tip.pig_racing_season": "Некоторые свинки бегают лучше или хуже в зависимости от сезона.",
  "society_tips.tip.suggestions": "Хотите предложить идею для модпака? Загляните в Discord разработчиков!",
  "society_tips.tip.prize_machine_two": "Использование призового билета даёт опыт во всех категориях навыков.",
  "society_tips.tip.milk": "Большая кружка молока даёт огромное количество насыщения при употреблении.",
  "society_tips.tip.beemonican": "Печать Пчелоники можно добыть в логове королевы.",
  "society_tips.tip.mystical_ocean": "Интересуетесь выживанием на островах и магией? Попробуйте Society: Mystical Ocean!",
  "society_tips.tip.husbandry_time": "Домашние животные начинают голодать только после того, как прошёл полный игровой день без еды.",
  "society_tips.tip.fish_season_night": "Некоторые виды рыб можно поймать исключительно в ночное время суток.",
  "society_tips.tip.quality_seed_maker": "Использование высококачественного урожая в создателе семян даёт семена аналогичного качества.",
  "society_tips.tip.mining_skill_leveling_one": "Добыча жеодных жил даёт большое количество опыта Горного дела.",
  "society_tips.tip.adventuring_skill_leveling": "Обыск сундуков с добычей даёт огромное количество опыта Приключений.",
  "society_tips.tip.husbandry_pigs": "Свиньи периодически выкапывают трюфели, если вы им достаточно нравитесь.",
  "society_tips.tip.prize_machine_one": "Некоторые плодовые деревья можно получить только через Призовой автомат.",
  "society_tips.tip.wise_oak": "Если найдёте дуб, утверждающий, что он мудр — остановитесь и выслушайте его.",
  "society_tips.tip.roe_value": "Чем ценнее пойманная рыба, тем дороже будет стоить её икра.",
  "society_tips.tip.balloons": "Не забывайте почаще смотреть в небо. Там может пролетать воздушный шарик с ценным грузом!",
  "society_tips.tip.enriched_bonemeal": "Обогащённая костная мука позволяет выращивать светящиеся ягоды и размножать чайные цветы.",
  "society_tips.tip.skill_books": "У странствующего торговца есть шанс купить особые книги навыков.",
  "society_tips.tip.pet_gifts": "Питомцы дарят особые предметы при достижении 10 сердец привязанности.",
  "society_tips.tip.trader": "Торговец продаёт улучшения для ремесленных станков.",
  "society_tips.tip.almanac": "Фермерский альманах содержит подробную информацию обо всех культурах, животных и питомцах.",
  "society_tips.tip.quality_preserves": "Одни ремесленные станки сохраняют качество исходных ингредиентов, а другие — нет.",
  "society_tips.tip.barkeeper": "Трактирщик продаёт еду с наценкой для тех, кому лень готовить самому. Вы прекрасно понимаете, о ком речь.",
  "society_tips.tip.slot_machine_prismatic": "Игровые автоматы с очень редким шансом могут выдать призматический осколок при игре крупными монетами.",
  "society_tips.tip.golden_egg_one": "Золотые яйца можно добыть инструментом с «Шёлковым касанием», чтобы приготовить майонез.",
  "society_tips.tip.husbandry_deployer": "Домашние животные недолюбливают холодную и бесчувственную руку механического сборщика.",
  "society_tips.tip.eternal_summer_jungle": "В биомах джунглей и саванны царит вечное лето.",
  "society_tips.tip.husbandry_magic_shears": "Магические ножницы вызывают странные и не очень приятные ощущения.",
  "society_tips.tip.hamsters": "Не кормите хомяков.",
  "society_tips.tip.husbandry_hand_feed": "Кормушки очень удобны для скота, но животные просто обожают, когда их кормят с рук.",
  "society_tips.tip.golden_egg_two": "Внутри золотых яиц может таиться нечто призматическое...",
  "society_tips.tip.lunchboxes": "Из ланч-боксов и пакетов для ланча можно есть напрямую, чтобы не захламлять инвентарь едой.",
  "society_tips.tip.preserves_jar": "Баночки для консервации утраивают стоимость помещённых в них фруктов и овощей.",
  "society_tips.tip.skull_cavern": "Пещера Черепа — самое опасное место во всей долине.",
  "society_tips.tip.cooking": "Кулинария всегда повышает итоговую ценность всех использованных ингредиентов.",
  "society_tips.tip.bank_meter": "Хотите знать, сколько денег лежит в банке? Купите банковский счётчик, чтобы он отображал баланс под шкалой сезона!",
  "society_tips.tip.crab_traps": "Ловушки для крабов работают вдвое быстрее в биомах рек и океанов.",
  "society_tips.tip.broken_clock": "Улучшение «Сломанные часы» сокращает время выдержки в бочках в два раза!",
  "society_tips.tip.sellable_search": "Введите «#sellable» в поиске JEI/EMI, чтобы увидеть все продаваемые предметы.",
  "society_tips.tip.sellable_products": "Введите «#farmer_products» в JEI/EMI, чтобы увидеть товары фермера. Это работает и для трёх других категорий!",
  "society_tips.tip.artisan_upgrades": "Ремесленные машины при разрушении роняют установленные в них улучшения.",
  "society_tips.tip.fish_season_rainy": "Некоторые виды рыб клюют только во время дождя.",
  "society_tips.tip.capitalism": "Капитализм.",
  "society_tips.tip.regret_crystals": "Не нравятся выбранные навыки? Купите кристалл сожаления у Ведьмы для сброса!",
  "society_tips.tip.rainbow_trout": "Радужная форель в рыбном пруду с вероятностью 1% может принести призматический осколок.",
  "society_tips.tip.wandering_trader_two": "Странствующий торговец регулярно предлагает редкие предметы мебели.",
  "society_tips.tip.snorp_sneep": "Снорп Снип Ɛ:",
  "society_tips.tip.sneep_snorp_one": "Снип Снорп",
  "society_tips.tip.sniffle_snaffle": "Сниффл Снаффл (Снаффл)",
  "society_tips.tip.sneep_snorp_two": "Снип Снорп :3",
  "society_tips.tip.fish_season": "Некоторые виды рыб можно поймать только в определённые сезоны года.",
  "society_tips.tip.fishing_skill_leveling": "Опыт Рыбной ловли также начисляется за создание снастей и сбор добычи из рыбных прудов.",
  "society_tips.tip.farming_skill_leveling": "Опыт Фермерства также начисляется за употребление приготовленных блюд и использование ремесленных машин.",
  "society_tips.tip.wandering_trader_one": "Странствующий торговец продаёт книги, дарующие очки опыта в навыках.",
  "society_tips.tip.tubasmoke_stick": "Дым тубатравки убивает...",
  "society_tips.tip.lets_go_gambling": "Давай сыграем в азартные игры! ...Эх, чёрт.",
  "society_tips.tip.husbandry_naming": "Пожалуйста, давайте клички своим домашним животным.",
  "society_tips.tip.balloon_seeds_two": "Чайные цветки можно найти в зелёных воздушных шарах.",
  "society_tips.tip.copycats": "Цинк используется для создания блоков-подражателей (Copycat). Это лучшие друзья строителя.",
  "society_tips.tip.quality_seeds": "Семена высокого качества дают более высокий шанс вырастить отборный урожай.",
  "society_tips.tip.passable_leaves": "Сквозь любую листву можно проходить насквозь, а ещё она смягчает падение с высоты.",
  "society_tips.tip.husbandry_fine_wool": "Только овцы и кролики способны давать тонкую шерсть премиум-класса.",
  "society_tips.tip.effects": "Не знаете, что делает эффект? Найдите его описание в меню JEI!",
  "society_tips.tip.furniture": "Любите украшать дом? Купите каталог мебели у Ведьмы!",
  "society_tips.tip.sol_onion": "Поддержание разнообразного рациона питания дарует вам постоянные полезные эффекты.",
  "society_tips.tip.fire_quartz_two": "Огненный кварц излучает слабое таинственное свечение.",
  "society_tips.tip.husbandry_babies": "Выращивание животного с самого детского возраста сделает его более привязанным к вам.",
  "society_tips.tip.balloon_seeds_one": "Семена хлопка можно найти в зелёных воздушных шарах.",
  "society_tips.tip.boomcat_slimes": "Слизни-бумкоты слегка взрываются, когда голодны.",
  "society_tips.tip.earth_crystals_two": "Кристаллы земли излучают крошечное количество света.",
  "society_tips.tip.husbandry_sheep_milk": "Овец можно доить, но на выработку молока у них уходит вдвое больше времени, чем у коров.",
  "society_tips.tip.etched": "Гравировальный стол позволяет создавать музыкальные пластинки по ссылкам с Bandcamp, Soundcloud или аудио-URL.",
  "society_tips.tip.fish_season_clear": "Некоторые виды рыб клюют исключительно в ясную и безоблачную погоду.",
  "society_tips.tip.husbandry_panda": "Панды собирают редкие фрукты с труднодоступных деревьев.",
  "society_tips.tip.husbandry_goat_milk": "Козье молоко ценится куда дороже коровьего. К сожалению, ради этого приходится терпеть самих коз.",
  "society_tips.tip.husbandry_goat_bison": "Козы и бизоны полны упрямства и норовят забодать всё, что попадается на глаза.",
  "society_tips.tip.beemonica_bear": "Найдёшь печать Пчелоники — найдёшь Медведя...",
  "society_tips.tip.fish_radar": "Не можете понять, где водится рыба? Рыбный радар покажет список всех доступных рыб на вашей текущей локации.",
  "society_tips.tip.string": "Ищете нити в начале игры? Рогоз и лён с радостью вам помогут.",
  "society_tips.tip.mining_skill_leveling_two": "Добыча кварца Незера — великолепный способ быстро накопить много опыта Горного дела.",
  "society_tips.tip.quest_book": "Если не знаете, что делать дальше — сверьтесь с книгой заданий!",
  "society_tips.tip.neptunium": "В ловушках для крабов с небольшим шансом можно выловить самородки нептуния.",
  "society_tips.tip.ribbit_hut": "Хижины квакушек-жабок могут автоматически собирать урожай и виноградные лозы.",
  "society_tips.tip.book_fair": "Книжную ярмарку можно вызвать по телефону в конце каждого сезона.",
  "society_tips.tip.skull_cavern_blocks": "Блоки, установленные вами в Пещере Черепа, не исчезнут за ночь.",
  "society_tips.tip.fish_pond_stack": "Рыбные пруды можно строить друг над другом по вертикали.",
  "society_tips.tip.sprinkler_inset": "Спринклеры можно встраивать вровень с пашней, и они всё равно будут увлажнять грядки.",
  "society_tips.tip.supreme_mayo": "Ни в коем случае не пейте Превосходный майонез.",
  "society_tips.tip.villager_friendship_one": "Каждый разговор с жителем городка укрепляет вашу дружбу.",
  "society_tips.tip.villager_friendship_two": "Нажмите Shift + ПКМ по жителю, чтобы вручить ему подарок. Главное — убедитесь, что он ему по душе.",
  "society_tips.tip.villager_ace": ":ace: Эйс любит держать запас батончиков мюсли в качестве походного перекуса.",
  "society_tips.tip.villager_aiden": ":aiden: Цветок раз в неделю — ключ к сердцу Эйдена...",
  "society_tips.tip.villager_leon": ":leon: Леон обожает бокал красного вина по вечерам.",
  "society_tips.tip.villager_haruna": ":haruna: Аквамагическая пыль напоминает Харуне о далёкой родине.",
  "society_tips.tip.villager_maria": ":maria: Мария считает подаренные цветы дешёвой манипуляцией.",
  "society_tips.tip.villager_caroline": ":caroline: Кэролайн уважает фермеров, умеющих находить подход к козам.",
  "society_tips.tip.villager_evelyne": ":evelyne: Эвелин считает ношение ведьминской шляпы профессиональным унижением.",
  "society_tips.tip.villager_veronica": ":veronica: У Вероники небольшая, но баснословно дорогая коллекция архивной моды.",
  "society_tips.tip.villager_carlos": ":carlos: Карлос обожает сытную домашнюю еду после долгих странствий по дорогам.",
  "society_tips.tip.longwings_size": "Чем крупнее пойманная бабочка или мотылёк, тем дороже они продаются.",
  "society_tips.tip.cafe_pricing": "Товары, продаваемые в кафе, получают +50% к базовой цене продажи.",
  "society_tips.tip.cafe_shed": "Большой сарай можно превратить в уютное кафе при помощи подходящего декора.",
  "society_tips.tip.selling_vs_keeping": "За деньги нельзя купить всё на свете, но почти всё на свете приносит деньги..."
};

// 1. Save locally in tips_translations folder
const tipsDir = path.join(__dirname, '../tips_translations');
if (!fs.existsSync(tipsDir)) {
    fs.mkdirSync(tipsDir, { recursive: true });
}

const localRuJson = path.join(tipsDir, 'society_tips_ru_ru.json');
fs.writeFileSync(localRuJson, JSON.stringify(tipsRu, null, 2), 'utf8');
console.log(`Saved locally: ${localRuJson} (${Object.keys(tipsRu).length} keys)`);

// 2. Sync directly to Modrinth profile
const modpackTipsDir = 'D:\\ModrinthApp\\profiles\\Society_ Sunlit Valley\\kubejs\\assets\\society_tips\\lang';
if (!fs.existsSync(modpackTipsDir)) {
    fs.mkdirSync(modpackTipsDir, { recursive: true });
}

const modpackRuJson = path.join(modpackTipsDir, 'ru_ru.json');
fs.writeFileSync(modpackRuJson, JSON.stringify(tipsRu, null, 2), 'utf8');
console.log(`Synchronized to game: ${modpackRuJson} (${Object.keys(tipsRu).length} keys)`);
