const fs = require('fs');
const path = require('path');
const { updateMarkdownFile } = require('./translation_helper');

const data = JSON.parse(fs.readFileSync(path.join(__dirname, 'extracted_keys_by_file.json'), 'utf8'));

// -------------------------------------------------------------
// 01_carpenter.md (Ace the Carpenter)
// Character: Energetic, direct, outdoor forager, lumberjack, craftsman, friend of Aiden and Caroline. Calls player on "ты" (@i).
// -------------------------------------------------------------
const carpenter = {
  "dialog.npc.carpenter.name": "Эйс",
  "dialog.npc.carpenter.chatter.description": "Разговор с Эйсом",
  "dialog.npc.carpenter.purchase_supplies": "Купить материалы",
  "dialog.npc.carpenter.invite_villagers": "Пригласить жителей",
  "dialog.npc.carpenter.build_farm": "Построить ферму",
  "dialog.npc.carpenter.build_village": "Построить город",
  "dialog.npc.carpenter.intro.description": "Знакомство с Эйсом",
  "dialog.npc.carpenter.intro.0.line_0": "Привет, путник! Меня зовут Эйс. Я здесь, чтобы помочь тебе построить поселение в Солнечной Долине.",
  "dialog.npc.carpenter.intro.0.line_1": "Если захочешь пригласить новых жителей, заглядывай ко мне — я помогу построить для них уютные дома.",
  "dialog.npc.carpenter.intro.0.line_2": "А если предпочитаешь строить сам, только скажи — у меня найдётся запас любых стройматериалов.",
  "dialog.npc.carpenter.intro.0.line_3": "Работы предстоит непочатый край! Приходи, если что-то понадобится!",

  "dialog.npc.carpenter.chatter_friendship0.0.line_0": "Чем я могу помочь тебе сегодня, @i?",
  "dialog.npc.carpenter.chatter_friendship0.1.line_0": "Нужны стройматериалы, @i?",
  "dialog.npc.carpenter.chatter_friendship0.2.line_0": "В чертежи из моего магазина уже включены все необходимые блоки!",
  "dialog.npc.carpenter.chatter_friendship0.2.line_1": "Не придётся бегать и крафтить всё вручную для каждой постройки — я обо всём позаботился!",
  "dialog.npc.carpenter.chatter_friendship0.3.line_0": "Дикие ягоды в лесу — отличный перекус во время работы на свежем воздухе!",
  "dialog.npc.carpenter.chatter_friendship0.4.line_0": "Не сбрасывай со счетов дикие травы вроде крапивы — из них получается отличный ароматный чай!",
  "dialog.npc.carpenter.chatter_friendship0.5.line_0": "Природа полна полезных растений, если знать, где и что искать.",
  "dialog.npc.carpenter.chatter_friendship0.6.line_0": "Я всегда стараюсь быть рядом, когда тебе нужна помощь со стройкой!",
  "dialog.npc.carpenter.chatter_friendship0.7.line_0": "Если не можешь найти нужное дерево в дикой природе, у меня в лавке есть саженцы!",
  "dialog.npc.carpenter.chatter_friendship0.8.line_0": "Заглядывай ко мне время от времени — у меня могут появиться новые приглашения для жителей.",
  "dialog.npc.carpenter.chatter_friendship0.9.line_0": "Эй, @i, как успехи? Уже освоился на новом месте?",
  "dialog.npc.carpenter.chatter_friendship0.10.line_0": "Уже разобрался с фермерством? Если пригласить кого-нибудь управлять рынком, сможешь покупать новые семена.",

  "dialog.npc.carpenter.chatter_friendship1.0.line_0": "Если найдёшь кристаллы земли в шахтах, обязательно сделай подсочники для деревьев.",
  "dialog.npc.carpenter.chatter_friendship1.0.line_1": "С разных пород древесины с их помощью можно собирать ценные смолы и соки.",
  "dialog.npc.carpenter.chatter_friendship1.1.line_0": "На днях во время прогулки я наткнулся на полуразрушенный и заросший фермерский дом...",
  "dialog.npc.carpenter.chatter_friendship1.1.line_1": "Интересно, почему прежний фермер бросил его?",
  "dialog.npc.carpenter.chatter_friendship1.2.line_0": "В моём магазине чертежей полно вариантов построек для твоей фермы.",
  "dialog.npc.carpenter.chatter_friendship1.2.line_1": "Мне потребуется лишь немного базовых материалов, чтобы возвести их.",
  "dialog.npc.carpenter.chatter_friendship1.3.line_0": "Чем могу помочь сегодня, @i?",
  "dialog.npc.carpenter.chatter_friendship1.3.line_1": "Какой же сегодня чудесный денёк!",
  "dialog.npc.carpenter.chatter_friendship1.4.line_0": "Картофель — одна из немногих культур, растущих в дикой природе! Я стараюсь выкапывать его при любой возможности.",
  "dialog.npc.carpenter.chatter_friendship1.5.line_0": "Стоит потратить время на улучшение инфраструктуры фермы.",
  "dialog.npc.carpenter.chatter_friendship1.5.line_1": "Ты можешь использовать картографическую карту, чтобы соединить дорожки и перемещаться быстрее!",
  "dialog.npc.carpenter.chatter_friendship1.6.line_0": "Я никогда не выхожу из дома без зелья возврата — заблудиться в глуши может быть опасно.",
  "dialog.npc.carpenter.chatter_friendship1.7.line_0": "Обязательно подготовься перед походом в шахту: недавно я заглянул в пещеру и встретил там опасных тварей.",
  "dialog.npc.carpenter.chatter_friendship1.8.line_0": "Чем планируешь заняться сегодня?",
  "dialog.npc.carpenter.chatter_friendship1.9.line_0": "А-а, привет, @i! Не могу долго болтать — собираюсь в большой поход в горы!",

  "dialog.npc.carpenter.chatter_friendship2.0.line_0": "Как продвигаются дела на ферме, @i?",
  "dialog.npc.carpenter.chatter_friendship2.1.line_0": "Фух, наконец-то я обжился на новом месте. Можно немного и перевести дух.",
  "dialog.npc.carpenter.chatter_friendship2.2.line_0": "Нужно что-нибудь построить сегодня?",
  "dialog.npc.carpenter.chatter_friendship2.3.line_0": "Строго говоря, ты не обязан покупать у меня хлев, но животные очень не любят мокнуть под дождём.",
  "dialog.npc.carpenter.chatter_friendship2.4.line_0": "Добротный сарай поможет держать все ремесленные станки в идеальном порядке.",
  "dialog.npc.carpenter.chatter_friendship2.5.line_0": "Столько открытых земель нужно обойти и разметить... К концу дня я просто валюсь с ног от усталости.",
  "dialog.npc.carpenter.chatter_friendship2.6.line_0": "Привет, @i! Что тебе нужно сегодня?",
  "dialog.npc.carpenter.chatter_friendship2.7.line_0": "Ты уже познакомился с Леоном? Тебе стоит получше узнать всех в городке!",
  "dialog.npc.carpenter.chatter_friendship2.7.line_1": "И я имею в виду абсолютно всех...",
  "dialog.npc.carpenter.chatter_friendship2.8.line_0": "Не забывай общаться со всеми, кого приглашаешь в этот город.",
  "dialog.npc.carpenter.chatter_friendship2.8.line_1": "Бросить родной дом и переехать в глухое поселение бывает довольно одиноко.",
  "dialog.npc.carpenter.chatter_friendship2.9.line_0": "Расспроси Марию о ручной белке! Они умеют собирать орехи и дикие ягоды.",
  "dialog.npc.carpenter.chatter_friendship2.9.line_1": "Пожалуй, мы с ними в чём-то похожи!",
  "dialog.npc.carpenter.chatter_friendship2.10.line_0": "Только не подумай лишнего — логист из меня просто никудышный!",
  "dialog.npc.carpenter.chatter_friendship2.10.line_1": "Кэролайн взяла на себя всю самую сложную организационную работу при основании городка.",
  "dialog.npc.carpenter.chatter_friendship2.11.line_0": "Обожаю тишину дикой природы и сбор лесных даров.",
  "dialog.npc.carpenter.chatter_friendship2.11.line_1": "Если замереть и прислушаться, можно услышать мягкие шаги лесных зверьков.",
  "dialog.npc.carpenter.chatter_friendship2.12.line_0": "Советую сохранять хотя бы по одному цветку каждого вида, найденного в природе.",
  "dialog.npc.carpenter.chatter_friendship2.12.line_1": "Они отлично размножаются от костной муки, в отличие от злаков и деревьев.",
  "dialog.npc.carpenter.chatter_friendship2.12.line_2": "К тому же Эйден просто обожает цветы, особенно редкие!",

  "dialog.npc.carpenter.chatter_friendship3.0.line_0": "Что для тебя сделать, @i?",
  "dialog.npc.carpenter.chatter_friendship3.1.line_0": "Привет, @i! Как жизнь?",
  "dialog.npc.carpenter.chatter_friendship3.2.line_0": "Вырастил что-нибудь новенькое в этом сезоне, @i?",
  "dialog.npc.carpenter.chatter_friendship3.3.line_0": "Кэролайн — единственный человек, который знает, откуда родом Харуна.",
  "dialog.npc.carpenter.chatter_friendship3.3.line_1": "Интересно, почему вокруг этого столько тайн... Но, наверное, лучше не лезть не в своё дело.",
  "dialog.npc.carpenter.chatter_friendship3.4.line_0": "А-а, @i, не хочешь составить мне компанию? Я как раз вырезаю деревянные панели.",
  "dialog.npc.carpenter.chatter_friendship3.5.line_0": "На днях Харуна пыталась научить меня рыбачить. Единственное, что я умудрился поймать на крючок — это её заколку для волос...",
  "dialog.npc.carpenter.chatter_friendship3.6.line_0": "Всегда с нетерпением жду сезона моховых ягод. Нет ничего лучше, чем рубить дерево и увидеть, как с ветки падает сочный зелёный плод!",
  "dialog.npc.carpenter.chatter_friendship3.7.line_0": "Деревья очень выносливы и растут почти в любой сезон. Хотя ели, как я заметил, терпеть не могут летнюю жару.",
  "dialog.npc.carpenter.chatter_friendship3.8.line_0": "Тебе стоит смастерить сачок для насекомых!",
  "dialog.npc.carpenter.chatter_friendship3.8.line_1": "Во время походов я встречал кучу редких бабочек и мотыльков.",

  "dialog.npc.carpenter.chatter_friendship4.0.line_0": "Эй, @i, как развивается твоя ферма?",
  "dialog.npc.carpenter.chatter_friendship4.1.line_0": "Как дела?",
  "dialog.npc.carpenter.chatter_friendship4.2.line_0": "Прости, не могу поболтать — я немного отстаю от плана по заготовке древесины на этой неделе.",
  "dialog.npc.carpenter.chatter_friendship4.3.line_0": "Кэролайн поручила мне изготовление мебели! Жаль только, что всё это пойдёт на экспорт в другие колонии.",
  "dialog.npc.carpenter.chatter_friendship4.4.line_0": "Копчёный лосось от Харуны — это нечто невероятное! Идеальный перекус для долгих походов по лесу.",
  "dialog.npc.carpenter.chatter_friendship4.5.line_0": "Я до сих пор не понял, что это за странные птицы... Надо будет расспросить Марию.",
  "dialog.npc.carpenter.chatter_friendship4.6.line_0": "Сушёные фрукты — отличная еда для путешествий. На рынке как раз продаётся дегидратор, если тебе интересно.",
  "dialog.npc.carpenter.chatter_friendship4.7.line_0": "Леон угостил меня образцами урожая этого сезона! Твои фермерские продукты просто пышут свежестью.",
  "dialog.npc.carpenter.chatter_friendship4.8.line_0": "Похоже, Эйден наточил мой топор, пока я не видел. Какая же добрая душа!",

  "dialog.npc.carpenter.chatter_friendship5.0.line_0": "Я искренне ценю всё, что Кэролайн сделала для этого городка.",
  "dialog.npc.carpenter.chatter_friendship5.0.line_1": "Со стороны это не всегда заметно, но она вложила душу и колоссальный труд ради каждого из нас.",
  "dialog.npc.carpenter.chatter_friendship5.1.line_0": "Интересно, сможем ли мы когда-нибудь помочь Харуне вернуться на родину...",
  "dialog.npc.carpenter.chatter_friendship5.1.line_1": "Хотя бы ненадолго повидаться. Не хотелось бы, чтобы она навсегда потеряла связь с домом.",
  "dialog.npc.carpenter.chatter_friendship5.2.line_0": "В прошлой экспедиции я встретил диких пингвинов! Надо обязательно поймать парочку для Марии.",
  "dialog.npc.carpenter.chatter_friendship5.3.line_0": "Как успехи на ферме?",
  "dialog.npc.carpenter.chatter_friendship5.4.line_0": "Обязательно снарядись как следует перед спуском в Пещеру Черепа.",
  "dialog.npc.carpenter.chatter_friendship5.4.line_1": "Не хочу, чтобы с тобой что-нибудь случилось.",
  "dialog.npc.carpenter.chatter_friendship5.5.line_0": "Надеюсь, твой день проходит удачно, @i!",
  "dialog.npc.carpenter.chatter_friendship5.6.line_0": "Я по-настоящему счастлив тому, что нам удалось здесь построить, @i.",
  "dialog.npc.carpenter.chatter_friendship5.7.line_0": "Грибные брёвна — отличный способ заработать на посадке деревьев, тебе обязательно стоит разместить их у себя на ферме!",
  "dialog.npc.carpenter.chatter_friendship5.8.line_0": "Мистические ивы такие красивые... Интересно, знает ли Кэролайн, где достать их саженцы?",
  "dialog.npc.carpenter.chatter_friendship5.9.line_0": "Вырастил что-нибудь новенькое в этом сезоне, @i?",
  "dialog.npc.carpenter.chatter_friendship5.10.line_0": "Как поживаешь, @i?",
  "dialog.npc.carpenter.chatter_friendship5.11.line_0": "Смена времён года наверняка доставляет хлопот твоей ферме. Я могу построить для тебя теплицу-другую, если нужно!",
  "dialog.npc.carpenter.chatter_friendship5.11.line_1": "Только сначала достань немного тепличного стекла.",
  "dialog.npc.carpenter.chatter_friendship5.12.line_0": "Леон просто без ума от красного вина, как же здорово, что я запас диких ягод для его приготовления.",
  "dialog.npc.carpenter.chatter_friendship5.13.line_0": "Ума не приложу, как Эйдену удаётся ковать столько промышленного железа для моих построек.",
  "dialog.npc.carpenter.chatter_friendship5.14.line_0": "Что для тебя смастерить, @i?",

  "dialog.npc.carpenter.gift_loved.0.line_0": "Кто тебе подсказал, что я люблю такое? Потрясающий подарок, @i!",
  "dialog.npc.carpenter.gift_loved.1.line_0": "Огромное спасибо, это просто невероятный подарок!",
  "dialog.npc.carpenter.gift_loved.2.line_0": "Ты замечательный друг, знаешь об этом, @i?",
  "dialog.npc.carpenter.gift_loved.3.line_0": "Спасибо, для меня это очень ценно.",
  "dialog.npc.carpenter.gift_loved.4.line_0": "Это невероятно пригодится мне в походах! Огромное спасибо, @i!",
  "dialog.npc.carpenter.gift_loved.5.line_0": "Ого, спасибо, @i! Такие широкие жесты значат для меня очень много!",

  "dialog.npc.carpenter.gift_liked.0.line_0": "Такие вещи очень выручают меня во время исследований диких земель.",
  "dialog.npc.carpenter.gift_liked.1.line_0": "Как мило с твоей стороны! Я как раз собирался раздобыть нечто подобное.",
  "dialog.npc.carpenter.gift_liked.2.line_0": "Ты прямо читаешь мои мысли, @i! У меня они как раз заканчивались!",
  "dialog.npc.carpenter.gift_liked.3.line_0": "Спасибо! Жду не дождусь окончания работы, чтобы опробовать это.",
  "dialog.npc.carpenter.gift_liked.4.line_0": "Очень приятно! Найти время в твоём плотном графике ради такого подарка — это дорогого стоит.",
  "dialog.npc.carpenter.gift_liked.5.line_0": "Я немного смущаюсь, когда мне дарят подарки, но поверь — мне правда очень нравится!",
  "dialog.npc.carpenter.gift_liked.6.line_0": "Спасибо, @i, такой знак внимания очень много для меня значит.",

  "dialog.npc.carpenter.gift_neutral.0.line_0": "Спасибо, @i! Приятно получить такой знак внимания.",
  "dialog.npc.carpenter.gift_neutral.1.line_0": "О, благодарю.",
  "dialog.npc.carpenter.gift_neutral.2.line_0": "Очень мило с твоей стороны.",
  "dialog.npc.carpenter.gift_neutral.3.line_0": "Спасибо!",
  "dialog.npc.carpenter.gift_neutral.4.line_0": "Сердечно благодарю, очень внимательно с твоей стороны.",
  "dialog.npc.carpenter.gift_neutral.5.line_0": "Такая вещь скрасит долгий рабочий день, спасибо!",
  "dialog.npc.carpenter.gift_neutral.6.line_0": "Спасибо за подарок.",
  "dialog.npc.carpenter.gift_neutral.7.line_0": "Ты вспомнил обо мне, @i? Это очень приятно.",

  "dialog.npc.carpenter.gift_disliked.0.line_0": "Ох...",
  "dialog.npc.carpenter.gift_disliked.1.line_0": "Мне это не особо нужно...",
  "dialog.npc.carpenter.gift_disliked.2.line_0": "Э-э... спасибо?",
  "dialog.npc.carpenter.gift_disliked.3.line_0": "Ясно... Пожалуйста, не дари мне такое больше.",
  "dialog.npc.carpenter.gift_disliked.4.line_0": "Похоже, выбор подарков — не самая сильная твоя сторона?",
  "dialog.npc.carpenter.gift_disliked.5.line_0": "Интересно, получится ли пустить это на древесное удобрение...",
  "dialog.npc.carpenter.gift_disliked.6.line_0": "Это Леон сказал тебе, что мне такое нравится? Не очень-то смешная шутка...",
  "dialog.npc.carpenter.gift_disliked.7.line_0": "Здорово, конечно, что ты не мусоришь где попало, но этому добру точно можно найти место получше!",
  "dialog.npc.carpenter.gift_disliked.8.line_0": "В смысле ты отдаёшь это мне? Зачем?",
  "dialog.npc.carpenter.gift_disliked.9.line_0": "С чего ты взял, что мне это понравится?",

  "dialog.npc.carpenter.gift_hated.0.line_0": "Это вопиющее неуважение. Отойди от меня.",
  "dialog.npc.carpenter.gift_hated.1.line_0": "Убери это от моего лица, бессовестный ты человек.",
  "dialog.npc.carpenter.gift_hated.2.line_0": "Надеюсь, проснувшись завтра утром, ты задумаешься о том, каким человеком становишься.",
  "dialog.npc.carpenter.gift_hated.3.line_0": "С таким хамским отношением к людям ты здесь далеко не уедешь.",
  "dialog.npc.carpenter.gift_hated.4.line_0": "Всё, что ты делаешь — это берёшь, берёшь и берёшь от окружающих.",
  "dialog.npc.carpenter.gift_hated.4.line_1": "И вот этим ты решил отплатить?",
  "dialog.npc.carpenter.gift_hated.5.line_0": "Я и не подозревал, что ты настолько неприятный человек.",
  "dialog.npc.carpenter.gift_hated.5.line_1": "Похоже, приезжать сюда было большой ошибкой.",
  "dialog.npc.carpenter.gift_hated.6.line_0": "...",
  "dialog.npc.carpenter.gift_hated.6.line_1": "Уйди от меня с этой дрянью.",
  "dialog.npc.carpenter.gift_hated.7.line_0": "Этот мир и так суров. Будешь совать мне такой мусор — останешься в полном одиночестве.",
  "dialog.npc.carpenter.gift_hated.8.line_0": "Чем я заслужил такое отношение?",
  "dialog.npc.carpenter.gift_hated.9.line_0": "Знаешь ли, я вовсе не обязан здесь оставаться.",

  "dialog.npc.carpenter.unique_five_gift.line_0": "Эй, @i, есть минутка поболтать? Хочу показать тебе, над чем я всё это время работал!",
  "dialog.npc.carpenter.unique_five_gift.line_1": "Это Блокопедия! Полный справочник всех строительных блоков, которые мне удалось раздобыть.",
  "dialog.npc.carpenter.unique_five_gift.line_2": "Зная, как сильно ты заботишься о нашем городке, я со спокойной душой доверяю плод своего скромного хобби тебе.",
  "dialog.npc.carpenter.unique_five_gift.line_3": "Правда, брёвна мистической ивы мне найти так и не удалось — пришлось просить об одолжении Кэролайн, чтобы изготовить пару блоков из них...",
  "dialog.npc.carpenter.unique_five_gift.line_4": "Я очень ценю всё, что ты сделал для городка, и надеюсь, это пригодится тебе при дальнейшем строительстве!",

  "dialog.npc.carpenter.dialog.need_to_buy.line_0": "Нужно что-то приобрести в лавке?",
  "dialog.npc.carpenter.dialog.need_to_buy.option_0": "Купить материалы",
  "dialog.npc.carpenter.dialog.need_to_buy.option_1": "Пригласить жителей",
  "dialog.npc.carpenter.dialog.need_to_buy.option_2": "Построить фермерские здания",
  "dialog.npc.carpenter.dialog.need_to_buy.option_3": "Построить деревенские здания"
};

updateMarkdownFile('01_carpenter.md', carpenter);
console.log('Carpenter translation complete!');
