


// if (true) {
//     let translationKeys = {};
//     [
//         { title: "mining_skill_fortune", content: "If you can't afford the Fortune enchantment early game, invest in the Mining skill tree Fortune nodes." },
//         { title: "slot_machine", content: "Using a coin on a slot machine will give you 3x the amount if you win!" },
//         { title: "auto_trader", content: "The Auto Trader can automate trades from shops." },
//         { title: "fire_quartz_one", content: "Fire Quartz can be found in the Nether and hot Skull Cavern biomes." },
//         { title: "earth_crystals_one", content: "Earth Crystals can be found in the overworld and certain Skull Cavern biomes." },
//         { title: "gold_slimes", content: "Gold Slimes will steal from your bank account when upset." },
//         { title: "nether_vacation", content: "The Nether is a great place for a vacation!" },
//         { title: "pig_racing", content: "It's pig racing!" },
//         { title: "pig_racing_season", content: "Some pigs will race better or worse in certain seasons." },
//         { title: "suggestions", content: "Want to make a suggestion for the pack? Join the Discord!" },
//         { title: "prize_machine_two", content: "Redeeming a Prize Ticket gives some experience in every category." },
//         { title: "milk", content: "Large Milk has a large amount of saturation when drank." },
//         { title: "beemonican", content: "The Beemonican Seal can be plundered from the queen." },
//         { title: "mystical_ocean", content: "Interested in survival island and magic mods? Try Society: Mystical Ocean!" },
//         { title: "husbandry_time", content: "Farm animals only get hungry after a full Minecraft day's worth of time has passed without food." },
//         { title: "fish_season_night", content: "Some fish can only be caught at night." },
//         { title: "quality_seed_maker", content: "Using high quality crops in a Seed Maker will make seeds with the same quality." },
//         { title: "mining_skill_leveling_one", content: "Mining Geode Nodes gives a large amount of Mining experience." },
//         { title: "adventuring_skill_leveling", content: "Looting Chests gives a large amount of Adventuring experience." },
//         { title: "husbandry_pigs", content: "Pigs will occasionally dig up Truffles if they like you enough." },
//         { title: "prize_machine_one", content: "Certain fruit trees can only be obtained through the Prize Machine." },
//         { title: "wise_oak", content: "If you find an oak tree that claims to be wise, take a moment to listen." },
//         { title: "roe_value", content: "The more valuable a fish is, the more valuable their roe will be." },
//         { title: "balloons", content: "Make sure to look at the sky every once in a while. There might be a balloon you can pop!" },
//         { title: "enriched_bonemeal", content: "Enriched Bonemeal can grow Glow Berries and duplicate tea flowers." },
//         { title: "skill_books", content: "Wandering Traders have a chance to sell special skill books." },
//         { title: "pet_gifts", content: "Pets will give you special items at 10 hearts of affection." },
//         { title: "trader", content: "The Trader sells upgrades to Artisan Machines." },
//         { title: "almanac", content: "The Farmer's Almanac has information on all Crops, Farm Animals, and Pets." },
//         { title: "quality_preserves", content: "Some Artisan Machines preserve the quality from ingredients, some don't." },
//         { title: "barkeeper", content: "The Barkeeper sells food at a premium for those too lazy to cook. You know who I'm talking about." },
//         { title: "slot_machine_prismatic", content: "Slot Machines may very rarely drop Prismatic Shards when using higher value coins." },
//         { title: "golden_egg_one", content: "Golden Eggs can be mined with Silk Touch to make mayo." },
//         { title: "husbandry_deployer", content: "Farm animals dislike the cold, unfeeling hand of a Deployer." },
//         { title: "eternal_summer_jungle", content: "Jungle and Savanna biomes are permanently in Summer." },
//         { title: "husbandry_magic_shears", content: "Magic Shears feel strange and a little unpleasant." },
//         { title: "hamsters", content: "Do not feed Hamsters." },
//         { title: "husbandry_hand_feed", content: "Feeding Troughs are convenient ways to feed animals, but they absolutely love being fed by hand." },
//         { title: "golden_egg_two", content: "Golden Eggs may contain something prismatic..." },
//         { title: "lunchboxes", content: "Lunchbags & Lunchboxes can be directly eaten out of to avoid inventory food clutter." },
//         { title: "preserves_jar", content: "Preserves Jars 3x the value of fruits and crops put in them." },
//         { title: "skull_cavern", content: "The Skull Cavern is the most dangerous area to visit." },
//         { title: "cooking", content: "Cooking will always increase the value of all ingredients." },
//         { title: "bank_meter", content: "Want to know how much cash you have in the Bank? Buy a Bank Meter to display it under the season!" },
//         { title: "crab_traps", content: "Crab Traps work twice as fast in River and Ocean biomes." },
//         { title: "broken_clock", content: "The Broken Clock upgrade reduces the time Aging Casks take by half!" },
//         { title: "sellable_search", content: "You can search '#sellable' in JEI/EMI to see all the sellable items." },
//         { title: "sellable_products", content: "You can search '#farmer_products' in JEI/EMI to see all the sellable Farmer Products items. This works for the other 3 types!" },
//         { title: "artisan_upgrades", content: "Artisan machines drop their upgrades when broken." },
//         { title: "fish_season_rainy", content: "Some fish can only be caught while it's raining." },
//         { title: "capitalism", content: "Capitalism." },
//         { title: "regret_crystals", content: "Don't like the skills you chose? Purchase a Regret Crystal from a Witch!" },
//         { title: "rainbow_trout", content: "Rainbow Trout in Fish Ponds have a 1% chance of giving Prismatic Shards." },
//         { title: "wandering_trader_two", content: "The Wandering Trader sells certain rare furniture drops reliably." },
//         { title: "snorp_sneep", content: "Snorp Sneep \u0190:" },
//         { title: "sneep_snorp_one", content: "Sneep Snorp" },
//         { title: "sniffle_snaffle", content: "Sniffle Snaffle (Snuffle)" },
//         { title: "sneep_snorp_two", content: "Sneep Snorp :3" },
//         { title: "fish_season", content: "Some fish can only be caught in specific seasons." },
//         { title: "fishing_skill_leveling", content: "Fishing experience also comes from crafting fishing equipment and harvesting from Fish Ponds." },
//         { title: "farming_skill_leveling", content: "Farming experience also comes from eating cooked meals and using Artisan Machines." },
//         { title: "wandering_trader_one", content: "The Wandering Trader sells books that give experience in skills." },
//         { title: "tubasmoke_stick", content: "Tubasmoke kills..." },
//         { title: "lets_go_gambling", content: "Let's go gambling! ...Aw dangit." },
//         { title: "husbandry_naming", content: "Please name your farm animals." },
//         { title: "balloon_seeds_two", content: "Tea Blossoms can be found in Green Balloons." },
//         { title: "copycats", content: "Zinc can be used to create Copycat blocks. They're a builder's best friend." },
//         { title: "quality_seeds", content: "High quality seeds have a higher chance of growing high quality crops." },
//         { title: "passable_leaves", content: "Any leaf block is able to be walked through, and can even cushion your fall." },
//         { title: "husbandry_fine_wool", content: "Only Sheep and Rabbits can produce Fine Wool." },
//         { title: "effects", content: "Don't know what an effect does? Search for it in JEI!" },
//         { title: "furniture", content: "Like decorating? Purchase a Furniture Catalog from the Witch!" },
//         { title: "sol_onion", content: "Maintaining a diet of diverse foods will provide you with constant buffs." },
//         { title: "fire_quartz_two", content: "Fire Quartz gives off low levels of light." },
//         { title: "husbandry_babies", content: "Raising a farm animal as a baby will make them like you more." },
//         { title: "balloon_seeds_one", content: "Cotton Seeds can be found in Green Balloons." },
//         { title: "boomcat_slimes", content: "Boomcat Slimes gently explode when hungry." },
//         { title: "earth_crystals_two", content: "Earth Crystals give off tiny amounts of light." },
//         { title: "husbandry_sheep_milk", content: "Sheep can be milked, but it takes twice as long to produce it as Cows." },
//         { title: "etched", content: "The Etching Table can make music discs from Bandcamp, Soundcloud, or sound URL links." },
//         { title: "fish_season_clear", content: "Some fish can only be caught while the weather is clear." },
//         { title: "husbandry_panda", content: "Pandas will forage fruits from difficult to obtain trees." },
//         { title: "husbandry_goat_milk", content: "A Goat's milk is much more valuable than a cow's. Unfortunately that means dealing with goats." },
//         { title: "husbandry_goat_bison", content: "Goats and Bison are filled with hatred and will ram everything in sight." },
//         { title: "beemonica_bear", content: "Find the Beemonican Seal, find the Bear..." },
//         { title: "fish_radar", content: "Can't figure out where to find a fish? A Fish Radar can be used to get the currently available fish at your location." },
//         { title: "string", content: "Looking for String early? Cattails and Flax can help you out." },
//         { title: "mining_skill_leveling_two", content: "Mining Nether Quartz is a great way to get a large amount of Mining experience." },
//         { title: "quest_book", content: "If you ever feel lost in progression, check out the quest book!" },
//         { title: "neptunium", content: "Crab Traps have a low chance of fishing up Neptunium Nuggets." },
//         { title: "ribbit_hut", content: "Ribbit Huts can harvest crops and Grapevine stems." },
//         { title: "book_fair", content: "The Book Fair can be called using the phone at the end of every season." },
//         { title: "skull_cavern_blocks", content: "Blocks you place in the Skull Cavern won't disappear overnight." },
//         { title: "fish_pond_stack", content: "Fish Ponds can stack vertically." },
//         { title: "sprinkler_inset", content: "Sprinklers can be placed at the same level as Farmland and still hydrate." },
//         { title: "supreme_mayo", content: "Do not drink Supreme Mayonnaise." },
//         { title: "villager_friendship_one", content: "Every time you talk to a villager they like you more." },
//         { title: "villager_friendship_two", content: "You can shift click on a villager to give them a gift. Just make sure they like it." },
//         { title: "villager_ace", content: ":ace: Ace likes to keep a stock of granola bars as field snacks." },
//         { title: "villager_aiden", content: ":aiden: A flower a week is the key to Aiden's heart..." },
//         { title: "villager_leon", content: ":leon: Leon loves a glass of red wine in the evening." },
//         { title: "villager_haruna", content: ":haruna: Aquamagical Dust reminds Haruna of home." },
//         { title: "villager_maria", content: ":maria: Maria views flowers as manipulative gifts." },
//         { title: "villager_caroline", content: ":caroline: Caroline respects a farmer that can handle goats." },
//         { title: "villager_evelyne", content: ":evelyne: Evelyne finds the witch hat professionally degreading." },
//         { title: "villager_veronica", content: ":veronica: Veronica has a small but expensive collection of archival fashion." },
//         { title: "villager_carlos", content: ":carlos: loves a home cooked meal after being on the road so long." },
//         { title: "longwings_size", content: "The larger a butterfly or moth is, the more it sells for." },
//         { title: "cafe_pricing", content: "Items you sell in a cafe have a +50% base price increase." },
//         { title: "cafe_shed", content: "Large Sheds can be made into a Cafe with some decor." },
//         { title: "selling_vs_keeping", content: "Money can't buy everything, but most things give you money..." },
//     ].forEach((tip) => {
//         translationKeys[`society_tips.tip.${tip.title}`] = tip.content;
//         JsonIO.write(`kubejs/assets/society/tips/${tip.title}.json`, {
//             "tip": {
//                 "translate": `society_tips.tip.${tip.title}`
//             }
//         });
//     })

//     JsonIO.write(`kubejs/assets/society_tips/lang/en_us.json`, translationKeys);
// }